= 了解更多信息
:allow-uri-read: 


NetApp SolidFire 存储系统可使用恢复出厂映像(Return to Factory Image、RTFI)过程将软件映像写入新节点或将节点还原到其原始出厂状态。RTFI过程会安全擦除所有现有数据和配置(如果有)、并安装未配置的NetApp Element 软件映像。RTFI进程可用于所有SolidFire 节点。

SolidFire 系统对所有Element软件安装都使用一个RTFI进程。其中包括由开发人员执行的内部手动安装、通过自动化框架测试自动安装、由服务工程师和客户现场安装以及由各个集成商和合作伙伴执行的安装。所有SolidFire 节点都使用相同的RTFI过程、无论所使用的机箱或节点类型如何、都可以自动修复任何问题。

本指南的目标受众是负责安装、配置、使用或解决存储相关问题的集成商。

* Linux：您对Linux系统有一些了解。
* 网络连接：您已熟悉服务器网络连接和网络存储、包括IP地址、网络掩码和网关。



WARNING: RTFI过程会对数据造成破坏、并安全地擦除节点中的所有数据和配置详细信息、然后安装新的操作系统。验证用于RTFI进程的节点是否在集群中处于非活动状态。

部署和安装RTFI International Organization for Standarding (ISO)映像并执行RTFI过程：

* xref:task_rtfi_deployment_and_install_options.adoc[RTFI部署和安装选项]
* xref:task_rtfi_process.adoc[执行RTFI过程]
* xref:task_rtfi_options_menu.adoc[RTFI选项菜单]




== 了解更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 和 Element 软件文档"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["早期版本的 NetApp SolidFire 和 Element 产品的文档"^]

