---
permalink: storage/concept-element-replication-create-custom-replication-policy.html 
sidebar: sidebar 
keywords: ontap, cli, create, custom, replication, policy, relationship, 
summary: 如果关系的默认策略不适用，您可以创建自定义复制策略。 
---
= 创建自定义复制策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在创建复制关系时使用默认策略或自定义策略。对于自定义统一复制策略、您必须定义一个或多个_RERUSE_、以确定初始化和更新期间传输的Snapshot副本。

如果关系的默认策略不适用，您可以创建自定义复制策略。例如、您可能希望在网络传输中压缩数据、或者修改SnapMirror尝试传输Snapshot副本的次数。

.关于此任务
复制策略的 _policy type_ 决定了它支持的关系类型。下表显示了可用的策略类型。

[cols="2*"]
|===


| Policy type | 关系类型 


 a| 
异步镜像
 a| 
SnapMirror灾难恢复



 a| 
镜像存储
 a| 
统一复制

|===
.步骤
. 创建自定义复制策略：
+
`snapmirror policy create -vserver _SVM_ -policy policy -type async-mirror|mirror-vault -comment _comment_ -tries _transfer_tries_ -transfer-priority low|normal -is-network-compression-enabled true|false`

+
有关完整的命令语法，请参见手册页。

+
从ONTAP 9。5开始、您可以使用参数指定为SnapMirror同步关系创建通用Snapshot副本计划的计划 `-common-snapshot-schedule`。默认情况下、SnapMirror同步关系的通用Snapshot副本计划为一小时。您可以为SnapMirror同步关系的Snapshot副本计划指定一个介于30分钟到两小时之间的值。

+
以下示例将为 SnapMirror 灾难恢复创建一个自定义复制策略，以便为数据传输启用网络压缩：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
以下示例将为统一复制创建自定义复制策略：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----


.完成后
对于"`mirrirr-vor`"策略类型、您必须定义规则来确定初始化和更新期间传输的Snapshot副本。

使用 `snapmirror policy show`命令验证是否已创建SnapMirror策略。有关完整的命令语法，请参见手册页。
