---
permalink: storage/concept_data_manage_volumes_quality_of_service_policies.html 
sidebar: sidebar 
keywords: qos policies, manage, volumes, create, edit, delete 
summary: '通过服务质量 \ （ QoS\ ）策略，您可以创建和保存可应用于多个卷的标准化服务质量设置。您可以从 "Management" 选项卡上的 "QoS Policies" 页面创建，编辑和删除 QoS 策略。' 
---
= 管理服务质量策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过服务质量（ QoS ）策略，您可以创建和保存可应用于多个卷的标准化服务质量设置。您可以从 "Management" 选项卡上的 "QoS Policies" 页面创建，编辑和删除 QoS 策略。


NOTE: 如果使用的是 QoS 策略，请勿对卷使用自定义 QoS 。自定义 QoS 将覆盖和调整卷 QoS 设置的 QoS 策略值。

https://www.youtube.com/embed/q9VCBRDtrnI?rel=0["NetApp 视频： SolidFire 服务质量策略"]

请参见 link:../concepts/concept_data_manage_volumes_solidfire_quality_of_service.html["性能和服务质量"]。

* 创建 QoS 策略
* 编辑 QoS 策略
* 删除 QoS 策略




== 创建 QoS 策略

您可以创建 QoS 策略并在创建卷时应用它们。

. 选择 * 管理 * > * QoS 策略 * 。
. 单击 * 创建 QoS 策略 * 。
. 输入 * 策略名称 * 。
. 输入最小 IOPS* ，最大 IOPS* 和突发 IOPS* 值。
. 单击 * 创建 QoS 策略 * 。




== 编辑 QoS 策略

您可以更改现有 QoS 策略的名称或编辑与该策略关联的值。更改 QoS 策略会影响与此策略关联的所有卷。

. 选择 * 管理 * > * QoS 策略 * 。
. 单击要编辑的 QoS 策略对应的 "Actions" 图标。
. 在显示的菜单中，选择 "* 编辑 " 。
. 在 * 编辑 QoS 策略 * 对话框中，根据需要修改以下属性：
+
** Policy name
** 最小 IOPS
** 最大 IOPS
** 突发 IOPS


. 单击 * 保存更改 * 。




== 删除 QoS 策略

您可以删除不再需要的 QoS 策略。删除 QoS 策略时，与该策略关联的所有卷都会保留 QoS 设置，但不会与某个策略关联。


NOTE: 如果您尝试取消卷与 QoS 策略的关联，则可以将该卷的 QoS 设置更改为自定义。

. 选择 * 管理 * > * QoS 策略 * 。
. 单击要删除的 QoS 策略对应的 "Actions" 图标。
. 在显示的菜单中，选择 * 删除 * 。
. 确认操作。




== 了解更多信息

* link:task_data_manage_volumes_remove_a_qos_policy_association_of_a_volume.html["删除卷的 QoS 策略关联"]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

