---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: 您可以管理 SolidFire 存储系统的集群管理员帐户。可用的集群管理员管理功能包括创建，删除和编辑集群管理员帐户，更改集群管理员密码以及配置 LDAP 设置以管理用户的系统访问。 
---
= 管理集群管理员用户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过创建，删除和编辑集群管理员帐户，更改集群管理员密码以及配置 LDAP 设置来管理用户的系统访问来管理 SolidFire 存储系统的集群管理员帐户。



== 存储集群管理员帐户类型

运行 NetApp Element 软件的存储集群中可以存在两种类型的管理员帐户：主集群管理员帐户和集群管理员帐户。

* * 主集群管理员帐户 *
+
此管理员帐户是在创建集群时创建的。此帐户是对集群具有最高访问级别的主管理帐户。此帐户类似于 Linux 系统中的 root 用户。您可以更改此管理员帐户的密码。

* * 集群管理员帐户 *
+
您可以为集群管理员帐户授予有限的管理访问权限，以便在集群中执行特定任务。分配给每个集群管理员帐户的凭据用于对存储系统中的 API 和 Element UI 请求进行身份验证。




NOTE: 要通过每节点 UI 访问集群中的活动节点，需要使用本地（非 LDAP ）集群管理员帐户。访问尚未加入集群的节点不需要帐户凭据。



== 查看集群管理员详细信息

. 要创建集群范围（非 LDAP ）的集群管理员帐户，请执行以下操作：
+
.. 单击 * 用户 * > * 集群管理员 * 。


. 在用户选项卡的集群管理员页面上，您可以查看以下信息。
+
** * ID * ：分配给集群管理员帐户的序列号。
** * 用户名 * ：创建集群管理员帐户时为其指定的名称。
** * 访问 * ：分配给用户帐户的用户权限。可能值：
+
*** 读取
*** 报告
*** nodes
*** 驱动器
*** volumes
*** —帐户
*** clusterAdmins
*** 管理员




+

NOTE: 所有权限均可用于管理员访问类型。

+
** * 类型 * ：集群管理员的类型。可能值：
+
*** 集群
*** ldap


** * 属性 * ：如果集群管理员帐户是使用 Element API 创建的，则此列将显示使用该方法设置的任何名称 - 值对。
+
请参见 link:../api/index.html["《 NetApp Element 软件 API 参考》"]。







== 创建集群管理员帐户

您可以创建具有允许或限制对存储系统特定区域的访问权限的新集群管理员帐户。设置集群管理员帐户权限时，系统会为您未分配给集群管理员的任何权限授予只读权限。

如果要创建 LDAP 集群管理员帐户，请确保在开始之前已在集群上配置 LDAP 。

link:task_system_manage_enable_ldap_authentication.html["使用 Element 用户界面启用 LDAP 身份验证"]

您可以稍后更改报告，节点，驱动器，卷，帐户的集群管理员帐户权限。 和集群级别访问。启用某个权限后，系统会为此级别分配写入访问权限。系统会为管理员用户授予对您未选择的级别的只读访问权限。

您也可以稍后删除系统管理员创建的任何集群管理员用户帐户。您不能删除在创建集群时创建的主集群管理员帐户。

. 要创建集群范围（非 LDAP ）的集群管理员帐户，请执行以下操作：
+
.. 单击 * 用户 * > * 集群管理员 * 。
.. 单击 * 创建集群管理员 * 。
.. 选择 * 集群 * 用户类型。
.. 输入帐户的用户名和密码并确认密码。
.. 选择要应用于帐户的用户权限。
.. 选中此复选框以同意最终用户许可协议。
.. 单击 * 创建集群管理员 * 。


. 要在 LDAP 目录中创建集群管理员帐户，请执行以下操作：
+
.. 单击 * 集群 * > * LDAP * 。
.. 确保已启用 LDAP 身份验证。
.. 单击 * 测试用户身份验证 * ，然后复制为用户或用户所属组之一显示的可分辨名称，以便您可以稍后粘贴。
.. 单击 * 用户 * > * 集群管理员 * 。
.. 单击 * 创建集群管理员 * 。
.. 选择 LDAP 用户类型。
.. 在 Distinguished Name 字段中，按照文本框中的示例输入用户或组的完整可分辨名称。或者，也可以从先前复制的可分辨名称中粘贴该名称。
+
如果可分辨名称属于某个组，则 LDAP 服务器上属于该组的任何用户都将拥有此管理员帐户的权限。

+
要添加 LDAP 集群管理员用户或组，用户名的常规格式为 "`ldap ： < 完整可分辨名称 >` " 。

.. 选择要应用于帐户的用户权限。
.. 选中此复选框以同意最终用户许可协议。
.. 单击 * 创建集群管理员 * 。






== 编辑集群管理员权限

您可以更改报告，节点，驱动器，卷，帐户的集群管理员帐户权限， 和集群级别访问。启用某个权限后，系统会为此级别分配写入访问权限。系统会为管理员用户授予对您未选择的级别的只读访问权限。

. 单击 * 用户 * > * 集群管理员 * 。
. 单击要编辑的集群管理员对应的 "Actions" 图标。
. 单击 * 编辑 * 。
. 选择要应用于帐户的用户权限。
. 单击 * 保存更改 * 。




== 更改集群管理员帐户的密码

您可以使用 Element UI 更改集群管理员密码。

. 单击 * 用户 * > * 集群管理员 * 。
. 单击要编辑的集群管理员对应的 "Actions" 图标。
. 单击 * 编辑 * 。
. 在更改密码字段中，输入新密码并进行确认。
. 单击 * 保存更改 * 。




== 了解更多信息

* link:task_system_manage_enable_ldap_authentication.html["使用 Element 用户界面启用 LDAP 身份验证"]
* link:concept_system_manage_manage_ldap.html["禁用 LDAP"]
* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

