---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: 如果一个或两个元数据驱动器发生故障，您可以通过将元数据驱动器重新添加到集群来恢复元数据驱动器。如果已在节点上启用 NetApp Element 功能，则可以在 MDSS UI 中执行恢复操作。 
---
= 基本 MDSS 驱动器故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果一个或两个元数据驱动器发生故障，您可以通过将元数据（或分区）驱动器重新添加到集群来恢复这些驱动器。如果已在节点上启用 NetApp Element 功能，则可以在 MDSS UI 中执行恢复操作。

如果节点中的一个或两个元数据驱动器发生故障，分区服务将关闭，并且两个驱动器中的数据将备份到节点中的不同驱动器。

以下场景概述了可能的故障情形，并提供了更正问题描述的基本建议：



== 系统分区驱动器出现故障

* 在这种情况下，插槽 2 会经过验证并恢复为可用状态。
* 必须重新填充系统分区驱动器，才能使分区服务恢复联机。
* 您应更换系统分区驱动器，当系统分区驱动器可用时，请同时添加该驱动器和插槽 2 驱动器。



NOTE: 您不能将插槽 2 中的驱动器本身添加为元数据驱动器。您必须同时将这两个驱动器重新添加到节点。



== 插槽 2 发生故障

* 在这种情况下，系统分区驱动器会经过验证并返回到可用状态。
* 您应将插槽 2 更换为备用驱动器，当插槽 2 可用时，请同时添加系统分区驱动器和插槽 2 驱动器。




== 系统分区驱动器和插槽 2 发生故障

* 您应将系统分区驱动器和插槽 2 更换为备用驱动器。当这两个驱动器都可用时，请同时添加系统分区驱动器和插槽 2 驱动器。




== 操作顺序

* 将故障硬件驱动器更换为备用驱动器（如果两个驱动器都发生故障，请同时更换这两个驱动器）。
* 重新填充驱动器并使其处于可用状态后，请将其重新添加到集群中。




== 验证操作

* 验证插槽 0 （或内部）和插槽 2 中的驱动器是否已在 "Active Drives" 列表中标识为元数据驱动器。
* 验证所有分区平衡是否已完成（至少 30 分钟内，事件日志中不会再显示移动分区消息）。




== 有关详细信息 ...

xref:task_troubleshoot_add_mdss_drives.adoc[添加 MDSS 驱动器]
