---
permalink: storage/concept_data_manage_vvol_manage_storage_containers.html 
sidebar: sidebar 
keywords: storage container, storage containers, about storage containers, cluster, vvols, create, view details, chap, edit, delete 
summary: 存储容器是在运行 Element 软件的集群上创建的 vSphere 数据存储库表示形式。 
---
= 管理存储容器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储容器是在运行 Element 软件的集群上创建的 vSphere 数据存储库表示形式。

此时将创建存储容器并将其绑定到 NetApp Element 帐户。在 Element 存储上创建的存储容器在 vCenter 和 ESXi 中显示为 vSphere 数据存储库。存储容器不会在 Element 存储上分配任何空间。它们仅用于从逻辑上关联虚拟卷。

每个集群最多支持四个存储容器。要启用 VVol 功能，至少需要一个存储容器。



== 创建存储容器

您可以在 Element UI 中创建存储容器，并在 vCenter 中发现它们。您必须至少创建一个存储容器，才能开始配置 VVol 支持的虚拟机。

开始之前，请在 Element UI 中为集群启用 VVol 功能。

.步骤
. 选择 * VVols* > * 存储容器 * 。
. 单击 * 创建存储容器 * 按钮。
. 在 * 创建新存储容器 * 对话框中输入存储容器信息：
+
.. 输入存储容器的名称。
.. 配置 CHAP 的启动程序和目标密钥。
+

TIP: 将 "CHAP Settings" 字段留空可自动生成密钥。

.. 单击 * 创建存储容器 * 按钮。


. 验证新存储容器是否显示在 * 存储容器 * 子选项卡的列表中。
+

NOTE: 由于 NetApp Element 帐户 ID 会自动创建并分配给存储容器，因此无需手动创建帐户。





== 查看存储容器详细信息

在 "VVols" 选项卡的 "Storage Containers" 页面上，您可以查看集群上所有活动存储容器的信息。

* * 帐户 ID* ：与存储容器关联的 NetApp Element 帐户的 ID 。
* * 名称 * ：存储容器的名称。
* * 状态 * ：存储容器的状态。可能值：
+
** Active ：存储容器正在使用中。
** locked ：存储容器已锁定。


* * PE Type* ：协议端点类型（ SCSI 是 Element 软件唯一可用的协议）。
* * 存储容器 ID* ：虚拟卷存储容器的 UUID 。
* * 活动虚拟卷 * ：与存储容器关联的活动虚拟卷的数量。




== 查看单个存储容器详细信息

您可以通过从 "VVols" 选项卡上的 "Storage Containers" 页面中选择单个存储容器来查看其存储容器信息。

* * 帐户 ID* ：与存储容器关联的 NetApp Element 帐户的 ID 。
* * 名称 * ：存储容器的名称。
* * 状态 * ：存储容器的状态。可能值：
+
** Active ：存储容器正在使用中。
** locked ：存储容器已锁定。


* * CHAP Initiator Secret* ：启动程序的唯一 CHAP 密钥。
* * CHAP Target Secret* ：目标的唯一 CHAP 密钥。
* * 存储容器 ID* ：虚拟卷存储容器的 UUID 。
* * 协议端点类型 * ：表示协议端点类型（ SCSI 是唯一可用的协议）。




== 编辑存储容器

您可以在 Element UI 中修改存储容器 CHAP 身份验证。

. 选择 * VVols* > * 存储容器 * 。
. 单击要编辑的存储容器的 * 操作 * 图标。
. 在显示的菜单中，选择 * 编辑 * 。
. 在 CHAP Settings 下，编辑用于身份验证的 Initiator Secret 和 Target Secret 凭据。
+

TIP: 如果不更改 CHAP 设置凭据，它们将保持不变。如果您将凭据字段留空，系统将自动生成新密码。

. 单击 * 保存更改 * 。




== 删除存储容器

您可以从 Element UI 中删除存储容器。

.您需要的内容
确保已从 VVol 数据存储库中删除所有虚拟机。

.步骤
. 选择 * VVols* > * 存储容器 * 。
. 单击要删除的存储容器的 * 操作 * 图标。
. 在显示的菜单中，选择 * 删除 * 。
. 确认操作。
. 刷新 * 存储容器 * 子选项卡中的存储容器列表，以确认此存储容器已被删除。

