---
permalink: storage/concept_intro_solidfire_software_interfaces.html 
sidebar: sidebar 
keywords: interfaces, integration, user interface, Plug-in, vCenter, API, node UIs, command line, snapshots, shadow copies, Element software, Element, Element UI, UI, manage storage, utilities, integration utilities 
summary: 您可以使用 NetApp Element 软件界面和集成实用程序管理 SolidFire 存储系统。 
---
= SolidFire 软件界面
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 NetApp Element 软件界面和集成实用程序管理 SolidFire 存储系统。

* * NetApp Element 软件用户界面 *
+
用于设置 SolidFire 存储，监控集群容量和性能以及管理多租户基础架构中的存储活动。Element 是 SolidFire 集群的核心存储操作系统。Element 软件可在集群中的所有节点上独立运行，并可使集群节点将资源组合在一起，并作为一个存储系统提供给外部客户端。Element 软件负责整个系统的所有集群协调，扩展和管理工作。软件界面基于 Element API 构建。

* * 适用于 vCenter Server* 的 NetApp Element 插件
+
用于配置和管理运行 Element 软件的存储集群。此插件为 VMware vSphere 中的 Element UI 提供了一个备用界面。

* * NetApp Element 软件 APi*
+
用于使用一组对象，方法和例程来管理 SolidFire 存储。Element API 基于 HTTPS 上的 JSON-RPC 协议。您可以通过启用 API 日志来监控 Element UI 中的 API 操作；这样，您可以查看向系统发出的方法。您可以同时启用请求和响应，以查看系统如何对发出的方法做出响应。

* * 管理节点 UIs*
+
管理节点包含两个 UI ：一个 UI 用于管理基于 REST 的服务，一个每节点 UI 用于管理网络和集群设置以及操作系统测试和实用程序。从 REST API UI 中，您可以访问与服务相关的 API 菜单，以控制管理节点上的管理服务。





== 其他集成实用程序和工具

虽然通常使用 NetApp Element ， NetApp Element API 和适用于 vCenter Server 的 NetApp Element 插件来管理存储，但您可以使用其他实用程序和工具。

* https://mysupport.netapp.com/products/p/vro.html["NetApp 下载： SolidFire vRO"]
+
通过 VMware vRealize Orchestrator ® ，可以方便地使用 SolidFire API 管理 SolidFire 存储系统。

* https://mysupport.netapp.com/products/p/elementsdk.html["NetApp 下载： Element SDK"]
+
用于使用以下工具管理 SolidFire 集群：

+
** SolidFire 命令行
** SolidFire Postman API 测试套件：使程序员能够使用一组 Postman 函数来测试 SolidFire API 调用。
** SolidFire PowerShell ：使程序员能够使用一组 Microsoft ® Windows ® PowerShell ® 函数，这些函数使用 SolidFire API 管理 SolidFire 存储系统。
** SolidFire SDK Java ：使程序员能够将 SolidFire API 与 Java ® 编程语言集成在一起。
** SolidFire SDK .NET ：使程序员能够将 SolidFire API 与 .NET 编程平台集成在一起。
** SolidFire SDK Python ：使程序员能够将 SolidFire API 与 Python （ TM ）编程语言集成在一起。


* https://mysupport.netapp.com/products/p/elementsra.html["NetApp 下载： SolidFire 存储复制适配器"]
+
与 VMware ® Site Recovery Manager （ SRM ）集成，可与复制的 SolidFire 存储集群（阵列）进行通信并执行支持的工作流。

* https://mysupport.netapp.com/products/p/elementvss.html["NetApp 下载： SolidFire VSS 提供程序"]
+
将 VSS 卷影副本与 SolidFire 快照和克隆集成在一起。


