---
permalink: storage/concept_troubleshoot_drives.html 
sidebar: sidebar 
keywords: troubleshoot, drives, ssd, swappable, solid-state drives 
summary: 您可以将发生故障的固态驱动器 \ （ SSD\ ）更换为替代驱动器。SolidFire 存储节点的 SSD 可热插拔。如果您怀疑 SSD 发生故障，请联系 NetApp 支持部门验证故障并指导您完成正确的解决方法操作步骤。NetApp 支持部门还会与您合作，根据您的服务级别协议获取一个替代驱动器。 
---
= 对驱动器进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将发生故障的固态驱动器（ SSD ）更换为替代驱动器。SolidFire 存储节点的 SSD 可热插拔。如果您怀疑 SSD 发生故障，请联系 NetApp 支持部门验证故障并指导您完成正确的解决方法操作步骤。NetApp 支持部门还会与您合作，根据您的服务级别协议获取一个替代驱动器。

在这种情况下，如何插拔意味着您可以从活动节点中删除故障驱动器，并将其更换为 NetApp 提供的新 SSD 驱动器。建议不要删除活动集群上的无故障驱动器。

您应维护 NetApp 支持部门建议的现场备件，以便在驱动器出现故障时可以立即更换。


NOTE: 出于测试目的，如果要通过从节点中拉出驱动器来模拟驱动器故障，则必须等待 30 秒，然后才能将驱动器重新插入驱动器插槽。

如果某个驱动器发生故障，双 Helix 会在集群中的其余节点之间重新分布该驱动器上的数据。同一节点上的多个驱动器故障不是问题描述，因为 Element 软件可防止同一节点上存在两个数据副本。发生故障的驱动器会导致以下事件：

* 数据将从驱动器中迁移。
* 整体集群容量会通过驱动器容量减少。
* 双 Helix 数据保护可确保有两个有效的数据副本。



IMPORTANT: 如果删除驱动器会导致存储空间不足，无法迁移数据，则 SolidFire 存储系统不支持删除该驱动器。



== 有关详细信息 ...

* xref:task_troubleshoot_remove_failed_drives.adoc[从集群中删除故障驱动器]
* xref:concept_troubleshoot_basic_mdss_drive_troubleshooting.adoc[基本 MDSS 驱动器故障排除]
* xref:task_troubleshoot_remove_mdss_drives.adoc[删除 MDSS 驱动器]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2844771["更换 SolidFire 存储节点的驱动器"]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2846859["更换 H600S 系列存储节点的驱动器"]
* link:../hardware/concept_h410s_h610s_info.html["H410S 和 H610S 硬件信息"]
* link:../hardware/concept_sfseries_info.html["SF 系列硬件信息"]

