---
permalink: storage/concept_intro_custom_protection_domains.html 
sidebar: sidebar 
keywords: Protection Domain layout,user-defined,custom layout 
summary: 您可以定义自定义保护域布局，其中每个节点都与一个且仅与一个自定义保护域相关联。默认情况下，每个节点都分配到同一个默认的自定义保护域。 
---
= 自定义保护域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以定义与特定机箱和节点布局匹配的自定义保护域布局。

如果未分配自定义保护域：

* 集群操作不受影响。
* 自定义级别既非容错级别，也非弹性级别。


在为集群配置自定义保护域时，可以从 Element Web UI 信息板中查看三种可能的保护级别：

* 不受保护：存储集群不受其中一个自定义保护域故障的保护。要修复此问题，请向集群添加额外的存储容量或重新配置集群的自定义保护域，以防止集群可能丢失数据。
* 容错：存储集群具有足够的可用容量，可防止其中一个自定义保护域发生故障后数据丢失。
* 故障恢复能力：存储集群具有足够的可用容量，可在其中一个自定义保护域发生故障后自行修复。修复过程完成后，如果其他域发生故障，集群将受到保护，不会丢失数据。


如果分配了多个自定义保护域，则每个子系统将为单独的自定义保护域分配重复项。如果无法做到这一点，则会还原为将重复项分配给不同的节点。每个子系统（例如箱，扇区，协议端点提供程序和集合）都独立执行此操作。

您可以使用 Element UI link:task_data_protection_configure_custom_protection_domains.html["配置自定义保护域"^]或者，您也可以使用以下 API 方法：

* link:../api/reference_element_api_getprotectiondomainlayout.html["GetProtectionDomainLayout"^] - 显示每个节点所在的机箱和自定义保护域。
* link:../api/reference_element_api_setprotectiondomainlayout.html["SetProtectionDomainLayout"^] - 用于为每个节点分配自定义保护域。




== 了解更多信息

link:../api/index.html["使用 Element API 管理存储"^]
