---
permalink: storage/concept_data_manage_volumes_solidfire_quality_of_service.html 
sidebar: sidebar 
keywords: qos policies, iops 
summary: SolidFire 存储集群可以按卷提供服务质量 \ （ QoS\ ）参数。您可以使用以下三个可配置参数来定义 QoS ，以保证集群性能（以每秒输入和输出数 \ （ IOPS\ ）为单位）：最小 IOPS ，最大 IOPS 和突发 IOPS 。 
---
= Quality of service
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 存储集群能够按卷提供服务质量（ QoS ）参数。您可以使用以下三个可配置参数来定义 QoS ，以保证集群性能（以每秒输入和输出数（ IOPS ）为单位）：最小 IOPS ，最大 IOPS 和突发 IOPS 。


NOTE: SolidFire Active IQ 提供了一个 QoS 建议页面，可提供有关最佳配置和设置 QoS 设置的建议。

IOPS 参数的定义方式如下：

* * 最小 IOPS*
+
存储集群为卷提供的最小可持续每秒输入输出数（ IOPS ）。为卷配置的最小 IOPS 是卷性能的保证级别。性能不会低于此级别。

* * 最大 IOPS*
+
存储集群为卷提供的最大可持续 IOPS 。如果集群 IOPS 级别非常高，则不会超过此 IOPS 性能级别。

* * 突发 IOPS*
+
在短时突发情形下允许的最大 IOPS 数。如果卷运行的 IOPS 低于最大 IOPS ，则会累积突发额度。如果性能级别变得非常高并被推送到最大级别，则允许在卷上短时突发 IOPS 。

+
当集群在集群 IOPS 利用率较低的状态下运行时， Element 软件将使用突发 IOPS 。

+
一个卷可以累积突发 IOPS ，并使用这些额度在设定的 " 突发期间 " 突发 IOPS ，使其高于其最大 IOPS ，直至达到突发 IOPS 级别。如果集群具有容纳此突发的容量，则卷的突发时间可长达 60 秒。

+
卷在其最大 IOPS 限制下运行的每秒累积一秒突发额度（最多 60 秒）。

+
突发 IOPS 有两种限制：

+
** 卷可以在数秒内突发超过其最大 IOPS ，该秒数等于卷累积的突发额度数。
** 当卷突发到其最大 IOPS 设置以上时，它将受到其突发 IOPS 设置的限制。因此，突发 IOPS 不会超过卷的突发 IOPS 设置。


* * 有效最大带宽 *
+
最大带宽是通过将 IOPS 数（基于 QoS 曲线）乘以 IO 大小计算得出的。

+
示例

+
100 min IOPS ， 1000 Max IOPS 和 1500 Burst IOPS 的 QoS 参数设置会对性能质量产生以下影响：

+
** 工作负载可以达到并保持最大 IOPS 1000 ，直到集群上明显出现工作负载争用 IOPS 的情况为止。然后， IOPS 会逐渐减少，直到所有卷上的 IOPS 都在指定的 QoS 范围内，并缓解对性能的争用。
** 所有卷上的性能都将推向最小 IOPS 100 。此级别不会低于最小 IOPS 设置，但在缓解工作负载争用后，此级别仍可能高于 100 IOPS 。
** 在一段持续时间内，性能不会超过 1000 IOPS 或低于 100 IOPS 。允许性能达到 1500 IOPS （突发 IOPS ），但仅适用于通过低于最大 IOPS 而累积突发额度的卷，并且仅允许短时间内运行。突发级别永远不会持续。



