---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: 运行 Element 软件的集群会生成集群故障，以便在集群容量即将用尽时向存储管理员发出警告。集群填充度分为三个级别，所有这些级别均显示在 NetApp Element UI 中：警告，错误和严重。 
---
= 了解集群填充度级别
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
运行 Element 软件的集群会生成集群故障，以便在集群容量即将用尽时向存储管理员发出警告。集群填充度分为三个级别，所有这些级别均显示在 NetApp Element UI 中：警告，错误和严重。

系统使用 BlockClusterFull 错误代码警告集群块存储填充度。您可以从 Element UI 的 Alerts 选项卡查看集群填充度严重性级别。

以下列表包含有关 BlockClusterFull 严重性级别的信息：

* * 警告 *
+
此警告可由客户配置，在集群的块容量接近错误严重性级别时显示。默认情况下，此级别设置为比错误级别低 3% ，可通过 Element UI 和 API 进行调整。您必须尽快添加更多容量或释放容量。

* * 错误 *
+
当集群处于此状态时，如果节点丢失，集群中的容量将不足以重建双 Helix 数据保护。当集群处于此状态时，所有新卷创建，克隆和快照都会被阻止。对于任何集群而言，此状态都不是安全状态，也不是建议的状态。您必须立即添加更多容量或释放容量。

* * 严重 *
+
之所以出现此严重错误，是因为集群已被占用 100% 。它处于只读状态，无法与集群建立新的 iSCSI 连接。达到此阶段后，您必须立即释放或添加更多容量。



系统使用 MetadataClusterFull 错误代码发出有关集群元数据存储填充度的警告。您可以从 Element UI 中 "Reporting" 选项卡的 "Overview" 页面上的 "Cluster Capacity" 部分查看集群元数据存储填充度。

以下列表包含有关 MetadataClusterFull 严重性级别的信息：

* * 警告 *
+
此警告可由客户配置，在集群的元数据容量接近错误严重性级别时显示。默认情况下，此级别设置为比错误级别低 3% ，可通过 Element API 进行调整。您必须尽快添加更多容量或释放容量。

* * 错误 *
+
当集群处于此状态时，如果节点丢失，集群中的容量将不足以重建双 Helix 数据保护。当集群处于此状态时，所有新卷创建，克隆和快照都会被阻止。对于任何集群而言，此状态都不是安全状态，也不是建议的状态。您必须立即添加更多容量或释放容量。

* * 严重 *
+
之所以出现此严重错误，是因为集群已被占用 100% 。它处于只读状态，无法与集群建立新的 iSCSI 连接。达到此阶段后，您必须立即释放或添加更多容量。




NOTE: 以下适用场景双节点集群阈值：

* 元数据填充度错误比严重程度低 20% 。
* 块填充度错误为 1 个块驱动器（包括孤立容量）低于严重值；这意味着它是两个块驱动器，其容量低于严重值。

