---
permalink: storage/reference_post_deploy_change_default_ssl_certificate.html 
sidebar: sidebar 
keywords: ssl certificate, SSL, private key, self-signed, cluster, nodes, user-defined certificate, API, change default certificate, certificate, Element API 
summary: 您可以使用 NetApp Element API 更改集群中存储节点的默认 SSL 证书和专用密钥。 
---
= 更改 Element 软件的默认 SSL 证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 NetApp Element API 更改集群中存储节点的默认 SSL 证书和专用密钥。

创建 NetApp Element 软件集群时，集群会创建一个唯一的自签名安全套接字层（ SSL ）证书和专用密钥，用于通过 Element UI ，每节点 UI 或 API 进行所有 HTTPS 通信。Element 软件支持自签名证书以及由可信证书颁发机构（ CA ）颁发和验证的证书。

您可以使用以下 API 方法获取有关默认 SSL 证书的详细信息并进行更改。

* * GetSSLCertificate *
+
您可以使用 link:../api/reference_element_api_getsslcertificate.html["GetSSLCertificate方法"] 检索有关当前安装的SSL证书的信息、包括所有证书详细信息。

* * 设置 SSLCertificate *
+
您可以使用 link:../api/reference_element_api_setsslcertificate.html["SetSSLCertificate方法"] 将集群和每节点SSL证书设置为您提供的证书和专用密钥。系统会验证证书和专用密钥，以防止应用无效证书。

* * 删除 SSLCertificer*
+
。 link:../api/reference_element_api_removesslcertificate.html["RemoveSSLCertificate方法"] 删除当前安装的SSL证书和专用密钥。然后，集群将生成新的自签名证书和专用密钥。




NOTE: 集群 SSL 证书会自动应用于添加到集群中的所有新节点。从集群中删除的任何节点都会还原为自签名证书，并且所有用户定义的证书和密钥信息都会从该节点中删除。



== 了解更多信息

* link:../mnode/reference_change_mnode_default_ssl_certificate.html["更改管理节点的默认SSL证书"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["在Element Software中设置自定义SSL证书有哪些要求？"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 和 Element 软件文档"]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

