---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: '系统会报告多种类型的事件；每个事件都是系统已完成的一项操作。事件可以是例行事件，正常事件或需要管理员注意的事件。"Event Log" 页面上的 "Event Types" 列指示系统中发生事件的部分。' 
---
= 事件类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系统会报告多种类型的事件；每个事件都是系统已完成的一项操作。事件可以是例行事件，正常事件或需要管理员注意的事件。"Event Log" 页面上的 "Event Types" 列指示系统中发生事件的部分。


NOTE: 系统不会在事件日志中记录只读 API 命令。

以下列表介绍了事件日志中显示的事件类型：

* apiEvent*
+
用户通过 API 或 Web UI 启动的事件，用于修改设置。

* * 二进制分配事件 *
+
与数据箱分配相关的事件。箱本质上是保存数据的容器，并在整个集群中进行映射。

* *binSyncEvent*
+
与在块服务之间重新分配数据相关的系统事件。

* * bsCheckEvent*
+
与块服务检查相关的系统事件。

* * bsKillEvent*
+
与块服务终止相关的系统事件。

* * bulkOpEvent*
+
与对整个卷执行的操作相关的事件，例如备份，还原，快照或克隆。

* * cloneEvent*
+
与卷克隆相关的事件。

* * clusterMasterEvent*
+
集群初始化或集群配置更改时显示的事件，例如添加或删除节点。

* 【csum_event】* cSumEvent*
+
与端到端校验和验证期间检测到校验和不匹配相关的事件。

+
检测到校验和不匹配的服务会在生成此事件后自动停止且不重新启动。

* * 数据事件 *
+
与读取和写入数据相关的事件。

* * dbEvent*
+
与集群中的集合节点维护的全局数据库相关的事件。

* * 驱动器事件 *
+
与驱动器操作相关的事件。

* * 加密 AtRestEvent*
+
与集群上的加密过程相关的事件。

* * 信号群事件 *
+
与增加或减少集合中的节点数相关的事件。

* * fibreChannelEvent*
+
与节点配置和连接相关的事件。

* * gcEvent*
+
与进程相关的事件每 60 分钟运行一次，用于回收块驱动器上的存储。此过程也称为垃圾收集。

* * ieEvent*
+
内部系统错误。

* * 安装事件 *
+
自动软件安装事件。正在待定节点上自动安装软件。

* * iSCSIEvent *
+
与系统中的 iSCSI 问题相关的事件。

* * 限制事件 *
+
与帐户或集群中接近允许的最大数量的卷或虚拟卷数相关的事件。

* * 维护模式事件 *
+
与节点维护模式相关的事件，例如禁用节点。

* 【网络事件】*网络事件*
+
与每个物理网络接口卡(NIC)接口的网络错误报告相关的事件。

+
如果接口的任何错误计数在10分钟的监控间隔内超过默认阈值1000、则会触发这些事件。这些事件适用于网络错误、例如收到的未命中、循环冗余检查(CRC)错误、长度错误、溢出错误和帧错误。

* * platformHardwareEvent*
+
与在硬件设备上检测到的问题相关的事件。

* * 远程集群事件 *
+
与远程集群配对相关的事件。

* * 计划程序事件 *
+
与计划快照相关的事件。

* * 服务事件 *
+
与系统服务状态相关的事件。

* * sliceEvent*
+
与分区服务器相关的事件，例如删除元数据驱动器或卷。

+
有三种类型的分区重新分配事件，其中包括有关分配卷的服务的信息：

+
** 翻转：将主服务更改为新的主服务
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 移动：将二级服务更改为新的二级服务
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** 修剪：从一组服务中删除卷
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* * snmpTrapEvent*
+
与 SNMP 陷阱相关的事件。

* * statEvent*
+
与系统统计信息相关的事件。

* * tsEvent*
+
与系统传输服务相关的事件。

* * 未预期异常 *
+
与意外系统异常相关的事件。

* *ureEvent*
+
与从存储设备读取时发生的不可恢复读取错误相关的事件。

* * vasaProviderEvent*
+
与 VASA （ vSphere 存储感知 API ）提供程序相关的事件。


