---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: 您可以使用存储节点的每节点 UI 创建或删除支持包，重置驱动器的配置设置以及重新启动网络或集群服务。 
---
= 使用每节点 UI 运行系统实用程序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用存储节点的每节点 UI 创建或删除支持包，重置驱动器的配置设置以及重新启动网络或集群服务。

您已登录到存储节点的每节点 UI 。

. 单击 * 系统实用程序 * 。
. 单击要运行的系统实用程序对应的按钮。
+
** * 控制电源 *
+
重新启动，重新启动或关闭节点。

+

IMPORTANT: 此操作会导致网络连接暂时断开。

+
指定以下参数：

+
*** 操作：选项包括重新启动和暂停（关闭）。
*** 唤醒延迟：节点恢复联机之前的任何其他时间。


** * 收集节点日志 *
+
在节点的 /tmp/bundles 目录下创建支持包。

+
指定以下参数：

+
*** Bundle Name ：创建的每个支持包的唯一名称。如果未提供名称，则使用 "supportbundle" 和节点名称作为文件名。
*** 额外的 args ：此参数将馈送到 sf_make_support_bundle 脚本。只有在 NetApp 支持部门要求时，才应使用此参数。
*** Timeout Sec ：指定等待每个 ping 响应的秒数。


** * 删除节点日志 *
+
删除节点上使用 * 创建集群支持包 * 或 CreateSupportBundle API 方法创建的任何当前支持包。

** * 重置驱动器 *
+
初始化驱动器并删除当前驻留在驱动器上的所有数据。您可以在现有节点或升级后的节点中重复使用此驱动器。

+
指定以下参数：

+
*** Drives ：要重置的设备名称（非驱动器 ID ）的列表。


** * 重置网络配置 *
+
帮助解决单个节点的网络配置问题，并将单个节点的网络配置重置为出厂默认设置。

** * 重置节点 *
+
将节点重置为出厂设置。此操作会删除所有数据，但会保留节点的网络设置。只有当节点未分配到集群且处于可用状态时，才能重置节点。

+

IMPORTANT: 使用此选项时，所有数据，软件包（软件升级），配置和日志文件都会从节点中删除。

** * 重新启动网络连接 *
+
重新启动节点上的所有网络服务。

+

IMPORTANT: 此操作可能发生原因会导致网络连接暂时断开。

** * 重新启动服务 *
+
重新启动节点上的 Element 软件服务。

+

IMPORTANT: 此操作可能发生原因会导致节点服务临时中断。您只能在 NetApp 支持部门的指示下执行此操作。

+
指定以下参数：

+
*** service ：要重新启动的服务名称。
*** 操作：要对服务执行的操作。选项包括启动，停止和重新启动。





