---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: 在 SolidFire 存储系统中，客户端可以通过用户帐户连接到节点上的卷。创建卷时，卷会分配给特定的用户帐户。 
---
= 使用CHAP处理帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在SolidFire 存储系统中、租户可以使用帐户使客户端能够连接到集群上的卷。帐户包含访问分配给它的卷所需的质询握手身份验证协议(Challenge-Handshake Authentication Protocol、CHAP)身份验证。创建卷时、卷会分配给特定帐户。

一个帐户最多可以分配 2 ， 000 个卷，但一个卷只能属于一个帐户。



== 创建帐户

您可以创建帐户以允许访问卷。

系统中的每个帐户名称都必须是唯一的。

. 选择 * 管理 * > * 帐户 * 。
. 单击 * 创建帐户 * 。
. 输入 * 用户名 * 。
. 在 * CHAP Settings* 部分中，输入以下信息：
+

NOTE: 将凭据字段留空可自动生成任一密码。

+
** 用于 CHAP 节点会话身份验证的 * 启动程序机密 * 。
** 用于 CHAP 节点会话身份验证的 * 目标机密 * 。


. 单击 * 创建帐户 * 。




== 查看帐户详细信息

您可以通过图形格式查看各个帐户的性能活动。

图形信息提供帐户的 I/O 和吞吐量信息。平均和峰值活动级别以 10 秒报告周期为增量进行显示。这些统计信息包括分配给帐户的所有卷的活动。

. 选择 * 管理 * > * 帐户 * 。
. 单击帐户对应的 "Actions" 图标。
. 单击 * 查看详细信息 * 。


下面是一些详细信息：

* * 状态 * ：帐户的状态。可能值：
+
** Active ：处于活动状态的帐户。
** locked ：已锁定的帐户。
** removed ：已删除并清除的帐户。


* * 活动卷 * ：分配给帐户的活动卷数。
* * 压缩 * ：分配给帐户的卷的压缩效率得分。
* * 重复数据删除 * ：分配给帐户的卷的重复数据删除效率得分。
* * 精简配置 * ：分配给帐户的卷的精简配置效率得分。
* * 整体效率 * ：分配给帐户的卷的整体效率得分。




== 编辑帐户

您可以编辑帐户以更改状态，更改 CHAP 密码或修改帐户名称。

修改帐户中的 CHAP 设置或从访问组中删除启动程序或卷可能会使发生原因启动程序意外丢失对卷的访问权限。要验证卷访问不会意外丢失，请始终注销将受帐户或访问组更改影响的 iSCSI 会话，并验证启动程序是否可以在完成启动程序设置和集群设置的任何更改后重新连接到卷。


IMPORTANT: 与管理服务关联的永久性卷将分配给在安装或升级期间创建的新帐户。如果您使用的是永久性卷，请勿修改或删除其关联帐户。

. 选择 * 管理 * > * 帐户 * 。
. 单击帐户对应的 "Actions" 图标。
. 在显示的菜单中，选择 * 编辑 * 。
. * 可选： * 编辑 * 用户名 * 。
. * 可选： * 单击 * 状态 * 下拉列表并选择其他状态。
+

IMPORTANT: 将状态更改为 * 已锁定 * 将终止与帐户的所有 iSCSI 连接，并且无法再访问此帐户。与帐户关联的卷会保留下来，但这些卷不能通过 iSCSI 发现。

. * 可选： * 在 * CHAP Settings* 下，编辑用于节点会话身份验证的 * 启动程序机密 * 和 * 目标机密 * 凭据。
+

NOTE: 如果不更改 * CHAP Settings* 凭据，它们将保持不变。如果将凭据字段留空，系统将生成新密码。

. 单击 * 保存更改 * 。




== 删除帐户

您可以删除不再需要的帐户。

删除帐户之前，请删除并清除与帐户关联的所有卷。


IMPORTANT: 与管理服务关联的永久性卷将分配给在安装或升级期间创建的新帐户。如果您使用的是永久性卷，请勿修改或删除其关联帐户。

. 选择 * 管理 * > * 帐户 * 。
. 单击要删除的帐户对应的 "Actions" 图标。
. 在显示的菜单中，选择 * 删除 * 。
. 确认操作。




== 了解更多信息

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

