---
permalink: storage/task_replication_pair_volumes_using_a_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, replication 
summary: 如果您没有远程集群的集群管理员凭据，则可以使用配对密钥将某个卷与远程集群上的另一个卷配对。 
---
= 使用配对密钥对卷配对
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您没有远程集群的集群管理员凭据，则可以使用配对密钥将某个卷与远程集群上的另一个卷配对。

.您需要什么？ #8217 ；将需要什么
* 确保包含卷的集群已配对。
* 确保远程集群上有一个要用于配对的卷。
+

NOTE: 您可以在配对过程完成后分配复制源和目标。复制源或目标可以是卷对中的任一卷。您应创建一个目标卷，该卷不包含任何数据，并且与源卷具有完全相同的特征，例如大小，卷的块大小设置（ 512e 或 4k ）以及 QoS 配置。如果您将现有卷分配为复制目标，则该卷上的数据将被覆盖。目标卷可以大于或等于源卷，但不能小于源卷。



.步骤
. 选择 * 管理 * > * 卷 * 。
. 单击要配对的卷的 * 操作 * 图标。
. 单击 * 配对 * 。
. 在 * 配对卷 * 对话框中，选择 * 开始配对 * 。
. 选择 * 我不 * 表示您无权访问远程集群。
. 从列表中选择 * 复制模式 * ：
+
** * 实时（异步） * ：在源集群上提交写入后，将向客户端确认这些写入。
** * 实时（同步） * ：在源集群和目标集群上提交写入后，将向客户端确认写入。
** * 仅限 Snapshot * ：仅复制在源集群上创建的快照。不会复制源卷中的活动写入。


. 单击 * 生成密钥 * 。
+

NOTE: 此操作将生成一个用于配对的文本密钥，并在本地集群上创建一个未配置的卷对。如果您未完成操作步骤，则需要手动删除卷对。

. 将配对密钥复制到计算机的剪贴板。
. 使配对密钥可供远程集群站点的集群管理员访问。
+

NOTE: 应以安全的方式对待卷配对密钥，使用时不应允许意外或不安全的访问。

+

IMPORTANT: 请勿修改配对密钥中的任何字符。如果修改此密钥，则此密钥将无效。

. 在远程集群 Element UI 中，选择 * 管理 * > * 卷 * 。
. 单击要配对的卷对应的 "Actions" 图标。
. 单击 * 配对 * 。
. 在 * 配对卷 * 对话框中，选择 * 完成配对 * 。
. 将配对密钥从另一个集群粘贴到 * 配对密钥 * 框中。
. 单击 * 完成配对 * 。
+
确认配对后，两个集群将开始连接要配对的卷。在配对过程中，您可以在 * 卷对 * 窗口的 * 卷状态 * 列中看到消息。卷对将显示 `PausedMisconfigured` ，直到分配了卷对的源和目标为止。

+
成功完成配对后，建议您刷新 Volumes 表以从配对卷的 * 操作 * 列表中删除 * 配对 * 选项。如果不刷新表，则 * 配对 * 选项仍可供选择。如果您再次选择 * 配对 * 选项，则会打开一个新选项卡，并且由于卷已配对，系统会在` Element UI 页面的 * 配对卷 * 窗口中报告一条 `STartVolumePairing Failed ： xVolumeAlreadyPaired" 错误消息。





== 了解更多信息

* xref:reference_replication_volume_pairing_messages.adoc[卷配对消息]
* xref:reference_replication_volume_pairing_warnings.adoc[卷配对警告]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[为配对卷分配复制源和目标]

