---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: 您可以使用NetApp Element UI重新同步原始源卷并执行故障恢复。本节介绍了初始源卷已丢失但初始集群仍完好的适用场景情形。有关如何还原到新集群的说明，请参见 NetApp 支持站点上的文档。 
---
= 源卷不再存在时执行故障恢复
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NetApp Element UI重新同步原始源卷并执行故障恢复。本节介绍了初始源卷已丢失但初始集群仍完好的适用场景情形。有关如何还原到新集群的说明，请参见 NetApp 支持站点上的文档。

.您需要的内容
* Element 卷和 ONTAP 卷之间的复制关系已断开。
* Element 卷已丢失，无法恢复。
* 原始卷名称显示为未找到。


.步骤
. 在 Element UI 中，找到为执行故障转移而中断的关系。
+
* 最佳实践： * 记下原始已断开关系的 SnapMirror 策略和计划详细信息。重新创建此关系时，需要此信息。

. 单击 * 操作 * 图标，然后单击 * 反向重新同步 * 。
. 确认操作。
+

NOTE: 反向重新同步操作将创建一个新关系，在此关系中，初始源卷和目标卷的角色将发生反转（这会导致两个关系，因为初始关系仍然存在）。由于原始卷不再存在，系统将创建一个与原始源卷具有相同卷名称和卷大小的新 Element 卷。新卷将分配一个名为 sm-recovery 的默认 QoS 策略，并与名为 sm-recovery 的默认帐户关联。您需要手动编辑 SnapMirror 创建的所有卷的帐户和 QoS 策略，以替换已销毁的原始源卷。

+
在反向重新同步操作中，最新快照中的数据将传输到新卷。您可以继续访问目标端上的活动卷并向其写入数据，但在稍后恢复初始主关系之前，您需要断开与活动卷连接的所有主机并执行 SnapMirror 更新。完成反向重新同步并确保目标端上的卷未连接任何活动会话且最新数据位于原始主卷上后，请继续执行以下步骤以完成故障恢复并重新激活原始主卷：

. 单击反向重新同步操作期间创建的反向关系的 * 操作 * 图标，然后单击 * 中断 * 。
. 单击源卷不存在的原始关系的 * 操作 * 图标，然后单击 * 删除 * 。
. 单击步骤 4 中中断的反向关系的 * 操作 * 图标，然后单击 * 反向重新同步 * 。
. 这样会反转源和目标，并导致与原始关系具有相同的卷源和卷目标关系。
. 单击 * 操作 * 图标和 * 编辑 * 以使用您记下的原始 QoS 策略和计划设置更新此关系。
. 现在，可以安全地删除步骤 6 中反向重新同步的反向关系。




== 了解更多信息

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror 故障恢复场景]
