---
permalink: storage/task_monitor_system_alerts.html 
sidebar: sidebar 
keywords: system alerts, view, cluster faults, system errors 
summary: 您可以查看有关系统中集群故障或错误的信息的警报。警报可以是信息，警告或错误，可以很好地指示集群的运行状况。大多数错误都会自动自行解决。 
---
= 查看系统警报
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以查看有关系统中集群故障或错误的信息的警报。警报可以是信息，警告或错误，可以很好地指示集群的运行状况。大多数错误都会自动自行解决。

您可以使用 ListClusterFaults API 方法自动监控警报。这样，您就可以收到有关发生的所有警报的通知。

. 在 Element UI 中，选择 * 报告 * > * 警报 * 。
+
系统每 30 秒刷新一次页面上的警报。

+
对于每个事件，您都会看到以下信息：

+
|===


| 项目 | Description 


 a| 
ID
 a| 
与集群警报关联的唯一 ID 。



 a| 
severity
 a| 
警报的重要性。可能值：

** 警告：可能很快需要关注的次要问题描述。仍允许系统升级。
** 错误：可能会降低发生原因性能或丢失高可用性（ HA ）的故障。错误通常不会影响服务。
** 严重：影响服务的严重故障。系统无法提供 API 或客户端 I/O 请求。在此状态下运行可能会导致数据丢失。
** 最佳实践：未使用建议的系统配置最佳实践。




 a| 
Type
 a| 
故障影响的组件。可以是节点，驱动器，集群，服务或卷。



 a| 
Node
 a| 
此故障所引用节点的节点 ID 。对于节点和驱动器故障，会提供此参数，否则会设置为 - （短划线）。



 a| 
驱动器 ID
 a| 
此故障所引用的驱动器的驱动器 ID 。对于驱动器故障，会提供此参数，否则会设置为 - （短划线）。



 a| 
错误代码
 a| 
一个描述性代码，用于指示故障的原因。



 a| 
详细信息
 a| 
故障的问题描述以及其他详细信息。



 a| 
Date
 a| 
记录故障的日期和时间。

|===
. 单击某个警报的 * 显示详细信息 * 可查看有关该警报的信息。
. 要查看页面上所有警报的详细信息，请单击详细信息列。
+
系统解决警报后，有关警报的所有信息（包括警报解决日期）将移至 "Resolved" （已解决）区域。





== 了解更多信息

* xref:reference_monitor_cluster_fault_codes.adoc[集群故障代码]
* link:api/index.html["使用 Element API 管理存储"]

