---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 您可以通过将启动程序映射到一组卷来创建卷访问组，以实现安全访问。然后，您可以使用帐户 CHAP 启动程序密钥和目标密钥授予对组中卷的访问权限。 
---
= 创建卷访问组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过将启动程序映射到一组卷来创建卷访问组，以实现安全访问。然后，您可以使用帐户 CHAP 启动程序密钥和目标密钥授予对组中卷的访问权限。

如果使用基于启动程序的 CHAP ，则可以为卷访问组中的单个启动程序添加 CHAP 凭据，从而提高安全性。这样，您就可以将此选项应用于已存在的卷访问组。

.步骤
. 单击 * 管理 * > * 访问组 * 。
. 单击 * 创建访问组 * 。
. 在 * 名称 * 字段中输入卷访问组的名称。
. 通过以下方式之一将启动程序添加到卷访问组：
+
[cols="25,75"]
|===
| 选项 | Description 


 a| 
添加光纤通道启动程序
 a| 
.. 在 "Add Initiators" 下，从 "Unbound Fibre Channel Initiators" 列表中选择一个现有光纤通道启动程序。
.. 单击 * 添加 FC 启动程序 * 。
+

NOTE: 如果单击 * 创建启动程序 * 链接，输入启动程序名称并单击 * 创建 * ，则可以在此步骤中创建启动程序。创建启动程序后，系统会自动将其添加到启动程序列表中。



格式示例如下：

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
添加 iSCSI 启动程序
 a| 
在 "Add Initiators" 下，从 "Initiators" 列表中选择一个现有启动程序。* 注： * 如果单击 * 创建启动程序 * 链接，输入启动程序名称并单击 * 创建 * ，则可以在此步骤中创建启动程序。创建启动程序后，系统会自动将其添加到启动程序列表中。

格式示例如下：

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: 您可以通过在 * 管理 * > * 卷 * > * 活动 * 列表中选择卷的操作菜单中的 * 查看详细信息 * 来找到每个卷的启动程序 IQN 。

修改启动程序时，可以将 requiredCHAP 属性切换为 True ，从而可以设置目标启动程序密钥。有关详细信息，请参见有关 ModifyInitiator API 方法的 API 信息。

link:../api/index.html["使用 Element API 管理存储"]

|===
. * 可选： * 根据需要添加更多启动程序。
. 在添加卷下，从 * 卷 * 列表中选择一个卷。
+
此卷将显示在 * 已连接卷 * 列表中。

. * 可选： * 根据需要添加更多卷。
. 单击 * 创建访问组 * 。




== 了解更多信息

xref:task_data_manage_vol_access_group_add_volumes.adoc[将卷添加到访问组]
