---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 您可以在对节点具有远程 IPMI 访问权限后立即更改默认的智能平台管理接口（ Intelligent Platform Management Interface ， IPMI ）管理员密码。如果存在任何安装更新，您可能需要执行此操作。 
---
= 更改节点的默认 IPMI 密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在对节点具有远程 IPMI 访问权限后立即更改默认的智能平台管理接口（ Intelligent Platform Management Interface ， IPMI ）管理员密码。如果存在任何安装更新，您可能需要执行此操作。

有关为节点配置 IPM 访问的详细信息，请参见 link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["为每个节点配置 IPMI"^]。

您可以更改以下节点的 IPM 密码：

* H410S 节点
* H610S 节点




== 更改 H410S 节点的默认 IPMI 密码

配置 IPMI 网络端口后，应尽快更改每个存储节点上 IPMI 管理员帐户的默认密码。

您应该已为每个存储节点配置 IPMI IP 地址。

.步骤
. 在可以访问 IPMI 网络的计算机上打开 Web 浏览器，然后浏览到此节点的 IPMI IP 地址。
. 在登录提示符处输入用户名 `admin` 和密码 `admin` 。
. 登录后，单击 * 配置 * 选项卡。
. 单击 * 用户 * 。
. 选择 `admin` user ，然后单击 * 修改用户 * 。
. 选中 * 更改密码 * 复选框。
. 在 * 密码 * 和 * 确认密码 * 字段中输入新密码。
. 单击 * 修改 * ，然后单击 * 确定 * 。
. 对具有默认 IPMI 密码的任何其他 H410S 节点重复此操作步骤。




== 更改 H610S 节点的默认 IPMI 密码

配置 IPMI 网络端口后，应尽快更改每个存储节点上 IPMI 管理员帐户的默认密码。

您应该已为每个存储节点配置 IPMI IP 地址。

.步骤
. 在可以访问 IPMI 网络的计算机上打开 Web 浏览器，然后浏览到此节点的 IPMI IP 地址。
. 在登录提示符处输入用户名 `root` 和密码 `calvin` 。
. 登录后，单击页面左上角的菜单导航图标以打开边栏抽屉。
. 单击 * 设置 * 。
. 单击 * 用户管理 * 。
. 从列表中选择 * 管理员 * 用户。
. 启用 * 更改密码 * 复选框。
. 在 * 密码 * 和 * 确认密码 * 字段中输入新的强密码。
. 单击页面底部的 * 保存 * 。
. 对具有默认 IPMI 密码的任何其他 H610S 节点重复此操作步骤。




== 了解更多信息

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

