---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: 在将网络设置提交到网络配置后，您可以测试对这些设置所做的更改。您可以运行测试以确保存储节点稳定，并且可以使其联机而不出现任何问题。 
---
= 使用每节点 UI 运行系统测试
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在将网络设置提交到网络配置后，您可以测试对这些设置所做的更改。您可以运行测试以确保存储节点稳定，并且可以使其联机而不出现任何问题。

您已登录到存储节点的每节点 UI 。

. 单击 * 系统测试 * 。
. 单击要运行的测试旁边的 * 运行测试 * ，或者选择 * 运行所有测试 * 。
+

NOTE: 运行所有测试操作可能非常耗时，只能在 NetApp 支持部门的指示下执行。

+
** * 测试连接的 Ensemble*
+
测试并验证与数据库集合的连接。默认情况下，此测试将对与此节点关联的集群使用集合。或者，您也可以提供其他集合来测试连接。

** * 测试连接 Mvip*
+
对指定的管理虚拟 IP （ MVIP ）地址执行 Ping 操作，然后对 MVIP 执行简单的 API 调用以验证连接。默认情况下，此测试会对与此节点关联的集群使用 MVIP 。

** * 测试连接 Svip*
+
使用与网络适配器上设置的最大传输单元（ Maximum Transmission Unit ， MTU ）大小匹配的 Internet 控制消息协议（ Internet Control Message Protocol ， ICMP ）数据包对指定的存储虚拟 IP （ Storage Virtual IP ， SVIP ）地址执行 Ping 操作。然后，它会作为 iSCSI 启动程序连接到 SVIP 。默认情况下，此测试会对与此节点关联的集群使用 SVIP 。

** * 测试硬件配置 *
+
测试所有硬件配置是否正确，验证固件版本是否正确，并确认所有驱动器均已安装并正常运行。这与出厂测试相同。

+

NOTE: 此测试需要大量资源，只有在 NetApp 支持部门要求时才应运行。

** * 测试本地连接 *
+
通过对每个节点上的集群 IP （ CIP ）执行 Ping 操作，测试与集群中所有其他节点的连接。只有当节点属于活动集群时，此测试才会显示在节点上。

** * 测试定位集群 *
+
验证节点是否可以找到在集群配置中指定的集群。

** * 测试网络配置 *
+
验证已配置的网络设置是否与系统上正在使用的网络设置匹配。此测试不用于检测节点主动加入集群时的硬件故障。

** * 测试 Ping*
+
对指定的主机列表执行 Ping 操作，或者如果未指定任何主机，则动态构建集群中所有已注册节点的列表，并对每个节点执行 Ping 操作以实现简单连接。

** * 测试远程连接 *
+
通过对每个节点上的集群 IP （ CIP ）执行 Ping 操作，测试与远程配对集群中所有节点的连接。只有当节点属于活动集群时，此测试才会显示在节点上。




