---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: 您可以配置自定义保护域以提高集群的故障恢复能力。 
---
= 配置自定义保护域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于包含两个以上存储节点的 Element 集群，您可以为每个节点配置自定义保护域。配置自定义保护域时，必须将集群中的所有节点分配给域。


TIP: 分配保护域时，节点之间将开始数据同步，某些集群操作将不可用，直到数据同步完成为止。为集群配置自定义保护域后，在添加新存储节点时，您无法为新节点添加驱动器，除非为此节点分配一个保护域并允许完成数据同步。请访问 link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["保护域文档"] 了解有关保护域的更多信息。


NOTE: 要使自定义保护域方案对集群有用，必须将每个机箱中的所有存储节点分配到同一个自定义保护域。为此，您需要根据需要创建尽可能多的自定义保护域（最小的自定义保护域方案为三个域）。最佳做法是，为每个域配置相同数量的节点，并尝试确保分配给特定域的每个节点的类型相同。

.步骤
. 单击 * 集群 * > * 节点 * 。
. 单击 * 配置保护域 * 。
+
在 * 配置自定义保护域 * 窗口中，您可以看到当前配置的保护域（如果有）以及各个节点的保护域分配。

. 输入新自定义保护域的名称，然后单击 * 创建 * 。
+
对需要创建的所有新保护域重复此步骤。

. 对于 * 分配节点 * 列表中的每个节点，单击 * 保护域 * 列中的下拉列表，然后选择要分配给该节点的保护域。
+

CAUTION: 在应用更改之前，请确保了解您的节点和机箱布局，您配置的自定义保护域方案以及该方案对数据保护的影响。如果您应用保护域方案并立即需要进行更改，则可能需要一段时间才能进行更改，因为应用配置后会发生数据同步。

. 单击 * 配置保护域 * 。


根据集群的大小，域之间的数据同步数据可能需要一段时间。数据同步完成后，您可以在 * 集群 * > * 节点 * 页面上查看自定义保护域分配， Element Web UI 信息板会在 * 自定义保护域运行状况 * 窗格中显示集群的保护状态。

应用自定义保护域配置后，您可能会看到以下错误：

|===


| error | Description | 解决方法： 


| SetProtectionDomainLayout 失败： ProtectionDomainLayout 会使 nodeID ｛ 9 ｝ 不可用。默认名称和非默认名称不能同时使用。 | 节点未分配保护域。 | 为节点分配保护域。 


| SetProtectionDomainLayout 失败：保护域类型 " 自定义 " 拆分保护域类型 " 机箱 " 。 | 多节点机箱中的节点分配的保护域与机箱中的其他节点不同。 | 确保为机箱中的所有节点分配相同的保护域。 
|===


== 了解更多信息

link:concept_intro_custom_protection_domains.html["自定义保护域"^]
link:../api/index.html["使用 Element API 管理存储"^]
