---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: 您可以在需要更多存储时或在创建集群后向集群添加节点。首次打开电源时，节点需要进行初始配置。配置节点后，它将显示在待定节点列表中，您可以将其添加到集群中。 
---
= 将节点添加到集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在需要更多存储时或在创建集群后向集群添加节点。首次打开电源时，节点需要进行初始配置。配置节点后，它将显示在待定节点列表中，您可以将其添加到集群中。

集群中每个节点上的软件版本必须兼容。将节点添加到集群时，集群会根据需要在新节点上安装集群版本的 NetApp Element 软件。

您可以向现有集群添加容量较小或较大的节点。您可以向集群添加更大的节点容量，以支持容量增长。必须成对向节点较小的集群添加较大的节点。这样，如果一个较大的节点发生故障，双 Helix 就可以有足够的空间来移动数据。您可以将较小的节点容量添加到较大的节点集群以提高性能。


NOTE: 如果新添加的节点占用的集群总容量超过 50% ，则此节点的某些容量将变为不可用（ " 孤立 " ），以使其符合容量规则。在添加更多存储之前，情况始终如此。如果添加的节点非常大，并且也不遵守容量规则，则先前的孤立节点将不再处于孤立状态，而新添加的节点将变为孤立状态。应始终成对添加容量，以避免发生这种情况。当节点变为孤立时，将引发 strandedCapacity 集群故障。

https://www.youtube.com/embed/2smVHWkikXY?rel=0["NetApp 视频：按需扩展：扩展 SolidFire 集群"^]

您可以向NetApp HCI 设备添加节点。

.步骤
. 选择 * 集群 * > * 节点 * 。
. 单击 * 待定 * 以查看待定节点列表。
+
添加节点的过程完成后、这些节点将显示在"Active nodes"列表中。在此之前，待定节点将显示在 "Pending Active" 列表中。

+
将待定节点添加到集群时、SolidFire 会在这些节点上安装集群的Element软件版本。这可能需要几分钟时间。

. 执行以下操作之一：
+
** 要添加单个节点，请单击要添加的节点对应的 * 操作 * 图标。
** 要添加多个节点，请选中要添加的节点对应的复选框，然后选中 * 批量操作 * 。* 注： * 如果要添加的节点的 Element 软件版本与集群上运行的版本不同，则集群会异步将此节点更新为集群主节点上运行的 Element 软件版本。更新节点后，它会自动将自己添加到集群中。在此异步过程中，节点将处于 pendingActive 状态。


. 单击 * 添加 * 。
+
此节点将显示在活动节点列表中。





== 了解更多信息

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[节点版本控制和兼容性]
