---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: SolidFire 系统使用卷配置存储。卷是 iSCSI 或光纤通道客户端通过网络访问的块设备。 
---
= 管理卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 系统使用卷配置存储。卷是 iSCSI 或光纤通道客户端通过网络访问的块设备。

从 "Management" 选项卡上的 "Volumes" 页面中，您可以在节点上创建，修改，克隆和删除卷。



== 创建卷

您可以创建一个卷并将该卷与给定帐户相关联。每个卷都必须与一个帐户相关联。通过此关联，帐户可以使用 CHAP 凭据通过 iSCSI 启动程序访问卷。

您可以在创建卷期间为卷指定 QoS 设置。

. 选择 * 管理 * > * 卷 * 。
. 单击 * 创建卷 * 。
. 在 * 创建新卷 * 对话框中，输入 * 卷名称 * 。
. 输入卷的总大小。
+

NOTE: 默认卷大小选择以 GB 为单位。您可以使用以 GB 或 GiB 为单位的大小创建卷：

+
** 1 GB = 1 000 000 000 字节
** 1GiB = 1 073 741 824 字节


. 为卷选择 * 块大小 * 。
. 单击 * 帐户 * 下拉列表，然后选择应有权访问卷的帐户。
+
如果帐户不存在，请单击 * 创建帐户 * 链接，输入新帐户名称，然后单击 * 创建 * 。此时将创建帐户并将其与新卷关联。

+

NOTE: 如果帐户数超过 50 个，则不会显示此列表。开始键入，自动完成功能将显示可能的值供您选择。

. 要设置 * 服务质量 * ，请执行以下操作之一：
+
.. 在 * 策略 * 下，您可以选择现有 QoS 策略（如果可用）。
.. 在 * 自定义设置 * 下，为 IOPS 设置自定义的最小值，最大值和突发值，或者使用默认 QoS 值。
+
最大或突发 IOPS 值大于 20 ， 000 IOPS 的卷可能需要较高的队列深度或多个会话，才能在单个卷上实现此级别的 IOPS 。



. 单击 * 创建卷 * 。




== 查看卷详细信息

. 选择 * 管理 * > * 卷 * 。
. 查看详细信息。
+
** * ID * ：系统为卷生成的 ID 。
** * 名称 * ：创建卷时为卷指定的名称。
** * 帐户 * ：分配给卷的帐户的名称。
** * 访问组 * ：卷所属的一个或多个卷访问组的名称。
** * 访问 * ：创建卷时分配给卷的访问类型。可能值：
+
*** Read / Write ：接受所有读取和写入。
*** Read Only ：允许所有读取活动；不允许写入。
*** Locked ：仅允许管理员访问。
*** ReplicationTarget ：指定为复制卷对中的目标卷。


** * 已用 * ：卷中已用空间的百分比。
** * 大小 * ：卷的总大小（以 GB 为单位）。
** * 快照 * ：为卷创建的快照数量。
** * QoS 策略 * ：用户定义的 QoS 策略的名称和链接。
** * 最小 IOPS* ：卷保证的最小 IOPS 数。
** * 最大 IOPS* ：卷允许的最大 IOPS 数。
** * 突发 IOPS* ：卷在短时间内允许的最大 IOPS 数。默认值为 15 ， 000 。
** * 属性 * ：已通过 API 方法以密钥 / 值对的形式分配给卷的属性。
** * 。 512e* ：指示卷上是否启用了 512e 。可能值：
+
*** 是的。
*** 否


** * 创建时间 * ：卷的创建日期和时间。






== 查看单个卷详细信息

您可以查看单个卷的性能统计信息。

. 选择 * 报告 * > * 卷性能 * 。
. 在卷列表中，单击某个卷对应的 "Actions" 图标。
. 单击 * 查看详细信息 * 。
+
页面底部将显示一个托盘，其中包含有关卷的常规信息。

. 要查看有关卷的更多详细信息，请单击 * 查看更多详细信息 * 。
+
系统将显示卷的详细信息以及性能图形。





== 编辑活动卷

您可以修改卷属性，例如 QoS 值，卷大小以及计算字节值时使用的度量单位。您还可以修改帐户访问权限以使用复制或限制对卷的访问。

在以下情况下，如果集群上有足够的空间，则可以调整卷大小：

* 正常运行条件。
* 正在报告卷错误或故障。
* 正在克隆此卷。
* 正在重新同步此卷。


.步骤
. 选择 * 管理 * > * 卷 * 。
. 在 * 活动 * 窗口中，单击要编辑的卷对应的 "Actions" 图标。
. 单击 * 编辑 * 。
. * 可选： * 更改卷的总大小。
+
** 您可以增加卷的大小，但不能减小卷的大小。一次调整大小操作只能调整一个卷的大小。垃圾收集操作和软件升级不会中断调整大小操作。
** 如果要调整用于复制的卷大小，则应首先增加分配为复制目标的卷的大小。然后，您可以调整源卷的大小。目标卷可以大于或等于源卷，但不能小于源卷。


+
默认卷大小选择以 GB 为单位。您可以使用以 GB 或 GiB 为单位的大小创建卷：

+
** 1 GB = 1 000 000 000 字节
** 1GiB = 1 073 741 824 字节


. * 可选： * 选择不同的帐户访问级别，如下所示：
+
** 只读
** 读 / 写
** 已锁定
** 复制目标


. * 可选： * 选择应有权访问卷的帐户。
+
如果帐户不存在，请单击 * 创建帐户 * 链接，输入新帐户名称，然后单击 * 创建 * 。此时将创建帐户并将其与卷关联。

+

NOTE: 如果帐户数超过 50 个，则不会显示此列表。开始键入，自动完成功能将显示可能的值供您选择。

. * 可选： * 要更改 * 服务质量 * 中的选择，请执行以下操作之一：
+
.. 在 * 策略 * 下，您可以选择现有 QoS 策略（如果可用）。
.. 在 * 自定义设置 * 下，为 IOPS 设置自定义的最小值，最大值和突发值，或者使用默认 QoS 值。
+

NOTE: 如果要在卷上使用 QoS 策略，则可以设置自定义 QoS 以删除与卷的 QoS 策略关联。自定义 QoS 将覆盖和调整卷 QoS 设置的 QoS 策略值。

+

TIP: 更改 IOPS 值时，应以十或百为单位递增。输入值需要有效的整数。

+

TIP: 为卷配置极高的突发值。这样，系统就可以更快地处理偶尔出现的大型块顺序工作负载，同时仍会限制卷的持续 IOPS 。



. 单击 * 保存更改 * 。




== 删除卷

您可以从 Element 存储集群中删除一个或多个卷。

系统不会立即清除已删除的卷；此卷在大约八小时内保持可用。如果在系统清除卷之前还原该卷，则该卷将恢复联机并还原 iSCSI 连接。

如果删除用于创建快照的卷，则其关联快照将变为非活动状态。清除已删除的源卷后，关联的非活动快照也会从系统中删除。


IMPORTANT: 与管理服务关联的永久性卷会在安装或升级期间创建并分配给新帐户。如果您使用的是永久性卷，请勿修改或删除这些卷或其关联帐户。

.步骤
. 选择 * 管理 * > * 卷 * 。
. 要删除单个卷，请执行以下步骤：
+
.. 单击要删除的卷对应的 "Actions" 图标。
.. 在显示的菜单中，单击 * 删除 * 。
.. 确认操作。


+
系统会将卷移动到 * 卷 * 页面上的 * 已删除 * 区域。

. 要删除多个卷，请执行以下步骤：
+
.. 在卷列表中，选中要删除的任何卷旁边的框。
.. 单击 * 批量操作 * 。
.. 在显示的菜单中，单击 * 删除 * 。
.. 确认操作。
+
系统会将这些卷移动到 * 卷 * 页面上的 * 已删除 * 区域。







== 还原已删除的卷

如果某个卷已被删除但尚未清除，您可以还原系统中的卷。系统会在删除卷后大约八小时自动清除该卷。如果系统已清除卷，则无法还原它。

. 选择 * 管理 * > * 卷 * 。
. 单击 * 已删除 * 选项卡可查看已删除卷的列表。
. 单击要还原的卷对应的 "Actions" 图标。
. 在显示的菜单中，单击 * 还原 * 。
. 确认操作。
+
此卷将放置在 * 活动 * 卷列表中，并恢复与此卷的 iSCSI 连接。





== 清除卷

清除卷后，该卷将从系统中永久删除。卷中的所有数据都将丢失。

系统会在删除后八小时自动清除已删除的卷。但是，如果要在计划的时间之前清除卷，则可以执行此操作。

. 选择 * 管理 * > * 卷 * 。
. 单击 * 已删除 * 按钮。
. 执行以下步骤以清除单个或多个卷。
+
[cols="25,75"]
|===
| 选项 | 步骤 


 a| 
清除单个卷
 a| 
.. 单击要清除的卷对应的 "Actions" 图标。
.. 单击 * 清除 * 。
.. 确认操作。




 a| 
清除多个卷
 a| 
.. 选择要清除的卷。
.. 单击 * 批量操作 * 。
.. 在显示的菜单中，选择 * 清除 * 。
.. 确认操作。


|===




== 克隆卷

您可以为单个卷或多个卷创建克隆，以便为数据创建时间点副本。克隆卷时，系统会创建卷的快照，然后为该快照引用的数据创建一份副本。这是一个异步过程，此过程所需的时间量取决于要克隆的卷大小和当前集群负载。

集群一次最多支持每个卷运行两个克隆请求，一次最多支持八个活动卷克隆操作。超过这些限制的请求将排队等待稍后处理。


NOTE: 操作系统在处理克隆卷方面有所不同。VMware ESXi 会将克隆的卷视为卷副本或快照卷。此卷将成为可用于创建新数据存储库的设备。有关挂载克隆卷和处理快照 LUN 的详细信息，请参见上的 VMware 文档 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["挂载 VMFS 数据存储库副本"] 和 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["管理重复的 VMFS 数据存储库"]。


IMPORTANT: 在通过克隆到较小的大小截断克隆的卷之前，请确保准备好分区，使其适合较小的卷。

.步骤
. 选择 * 管理 * > * 卷 * 。
. 要克隆单个卷，请执行以下步骤：
+
.. 在 * 活动 * 页面上的卷列表中，单击要克隆的卷对应的 "Actions" 图标。
.. 在显示的菜单中，单击 * 克隆 * 。
.. 在 * 克隆卷 * 窗口中，输入新克隆的卷的卷名称。
.. 使用 * 卷大小 * 自旋框和列表为卷选择一个大小和度量单位。
+

NOTE: 默认卷大小选择以 GB 为单位。您可以使用以 GB 或 GiB 为单位的大小创建卷：

+
*** 1 GB = 1 000 000 000 字节
*** 1GiB = 1 073 741 824 字节


.. 选择新克隆卷的访问类型。
.. 从 * 帐户 * 列表中选择要与新克隆的卷关联的帐户。
+

NOTE: 如果您单击 * 创建帐户 * 链接，输入帐户名称并单击 * 创建 * ，则可以在此步骤中创建帐户。创建帐户后，系统会自动将其添加到 * 帐户 * 列表中。



. 要克隆多个卷，请执行以下步骤：
+
.. 在 * 活动 * 页面上的卷列表中，选中要克隆的任何卷旁边的框。
.. 单击 * 批量操作 * 。
.. 在显示的菜单中，选择 * 克隆 * 。
.. 在 * 克隆多个卷 * 对话框的 * 新卷名称前缀 * 字段中，输入克隆卷的前缀。
.. 从 * 帐户 * 列表中选择要与克隆卷关联的帐户。
.. 选择克隆卷的访问类型。


. 单击 * 开始克隆 * 。
+

NOTE: 增加克隆的卷大小会导致新卷在卷末尾具有额外的可用空间。根据卷的使用方式，您可能需要在可用空间中扩展分区或创建新分区来利用它。





== 有关详细信息 ...

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

