---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: 您必须先配置各个节点，然后才能将其添加到集群中。在机架单元中安装节点并为其布线并打开其电源后，您可以使用每节点 UI 或节点终端用户界面配置节点网络设置。 
---
= 配置存储节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须先配置各个节点，然后才能将其添加到集群中。在机架单元中安装节点并为其布线并打开其电源后，您可以使用每节点 UI 或节点终端用户界面（ TUI ）配置节点网络设置。在继续操作之前，请确保您已获得节点的必要网络配置信息。

配置存储节点有两个选项：

* <<Configure a storage node using the per-node UI,每节点 UI>>：使用每节点 UI (https://<node_management_IP>:442)[] 配置节点网络设置。
* <<Configure a storage node using the TUI,TUI>>：使用节点终端用户界面（ TUI ）配置节点。


您不能将使用 DHCP 分配的 IP 地址的节点添加到集群中。您可以使用 DHCP IP 地址在每节点 UI ， TUI 或 API 中对节点进行初始配置。在此初始配置期间，您可以添加静态 IP 地址信息，以便将节点添加到集群中。

完成初始配置后，您可以使用节点的管理 IP 地址访问此节点。然后，您可以更改节点设置，将其添加到集群或使用此节点创建集群。您还可以使用 Element 软件 API 方法配置新节点。


NOTE: 从 Element 11.0 开始，可以为节点的管理网络配置 IPv4 ， IPv6 或这两个地址。此适用场景同时用于存储节点和管理节点，但不支持 IPv6 的管理节点 11.3 及更高版本除外。创建集群时， MVIP 只能使用一个 IPv4 或 IPv6 地址，并且必须在所有节点上配置相应的地址类型。



== 使用每节点 UI 配置存储节点

您可以使用每节点用户界面配置节点。

.关于此任务
* 您可以将节点配置为具有 IPv4 或 IPv6 地址。
* 要访问节点，需要使用 TUI 中显示的 DHCP 地址。您不能使用 DHCP 地址向集群添加节点。
+

IMPORTANT: 您应该为不同的子网配置管理（绑定 1G ）和存储（绑定 10G ）接口。通过绑定 1G 接口发送存储流量时，为同一子网发生原因路由问题配置了绑定 1G 和绑定 10G 接口。如果必须使用同一子网传输管理和存储流量，请手动配置管理流量以使用绑定 10G 接口。您可以使用每个节点 UI 的 * 集群设置 * 页面对每个节点执行此操作。



.步骤
. 在浏览器窗口中，输入节点的 DHCP IP 地址。
+
要访问此节点，必须添加扩展名 ` ： 442` ；例如， https://172.25.103.6:442[]。

+
此时将打开 * 网络设置 * 选项卡，并显示 * 绑定 1G* 部分。

. 输入 1G 管理网络设置。
. 单击 * 应用更改 * 。
. 单击 * 绑定 10G* 以显示 10G 存储网络设置。
. 输入 10G 存储网络设置。
. 单击 * 应用更改 * 。
. 单击 * 集群设置 * 。
. 输入 10G 网络的主机名。
. 输入集群名称。
+

IMPORTANT: 必须先将此名称添加到所有节点的配置中，然后才能创建集群。集群中的所有节点都必须具有相同的集群名称。集群名称区分大小写。

. 单击 * 应用更改 * 。




== 使用 TUI 配置存储节点

您可以使用终端用户界面（ Terminal User Interface ， TUI ）对新节点执行初始配置。

您应该为不同的子网配置绑定 1G （管理）和绑定 10G （存储）接口。为同一子网配置的绑定 1G 和绑定 10G 接口会在通过绑定 1G 接口发送存储流量时导致路由问题。如果必须使用同一子网传输管理和存储流量，请手动配置管理流量以使用绑定 10G 接口。您可以使用 Element UI 的 * 集群 * > * 节点 * 页面对每个节点执行此操作。

.步骤
. 将键盘和显示器连接到节点，然后打开节点电源。
+
TUI 的 NetApp 存储主菜单将显示在 tty1 终端上。

+

NOTE: 如果节点无法访问配置服务器， TUI 将显示一条错误消息。请检查配置服务器连接或网络连接以解决此错误。

. 选择 * 网络 * > * 网络配置 * 。
+

TIP: 要在菜单中导航，请按向上或向下箭头键。要移至其他按钮或按钮中的字段，请按 * 选项卡 * 。要在字段之间导航，请使用向上或向下箭头键。

. 选择 * 绑定 1G （管理） * 或 * 绑定 10G （存储） * 以配置节点的 1G 和 10G 网络设置。
. 对于绑定模式和状态字段，按 * 选项卡 * 选择帮助按钮并确定可用选项。
+
集群中的所有节点都必须具有相同的集群名称。集群名称区分大小写。如果 DHCP 服务器在具有可用 IP 地址的网络上运行，则 1GbE 地址将显示在 "Address" 字段中。

. 按 * 选项卡 * 选择 * 确定 * 按钮并保存更改。
+
节点将处于待定状态，可以添加到现有集群或新集群。





== 了解更多信息

* https://www.netapp.com/data-storage/solidfire/documentation["SolidFire 和 Element 资源页面"^]
* https://docs.netapp.com/us-en/vcp/index.html["适用于 vCenter Server 的 NetApp Element 插件"^]

