---
permalink: setup/task_setup_configure_fqdn_web_ui_access.html 
sidebar: sidebar 
keywords:  
summary: 使用安装了 NetApp Element 软件 12.2 或更高版本的 NetApp HCI ，您可以使用完全限定域名 \ （ FQDN\ ）访问存储集群 Web 界面。如果要使用 FQDN 访问 Web 用户界面，例如 Element Web UI ，每节点 UI 或管理节点 UI ，则必须先添加存储集群设置以确定集群使用的 FQDN 。 
---
= 配置完全限定域名 Web UI 访问
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 NetApp Element 软件 12.2 或更高版本的 NetApp HCI ，您可以使用完全限定域名（ FQDN ）访问存储集群 Web 界面。如果要使用 FQDN 访问 Web 用户界面，例如 Element Web UI ，每节点 UI 或管理节点 UI ，则必须先添加存储集群设置以确定集群使用的 FQDN 。

通过此过程，集群可以正确重定向登录会话，并改进与外部服务的集成，例如用于多因素身份验证的密钥管理器和身份提供程序。

.您需要什么？ #8217 ；将需要什么
* 此功能需要 Element 12.2 或更高版本以及管理服务版本 2.14 或更高版本。
* 要使用 REST API ，必须已部署运行 11.5 或更高版本的管理节点。


.步骤
. 确保为网络环境正确配置了 Element 存储节点和 mNode 的 DNS ，以便可以解析环境中的 FQDN 。要设置 DNS ，请转到存储节点的每节点 UI 和管理节点，然后选择 * 网络设置 * > * 管理网络 * 。
+
.. 存储节点的每节点 UI ： `https://<storage_node_management_IP>:442`
.. 管理节点的每节点 UI ： `https://<management_node_IP>:442`


. 访问 Element API 并使用创建以下集群接口首选项 link:../api/reference_element_api_createclusterinterfacepreference.html["CreateClusterInterfacePreference"] API 方法，插入集群 MVIP FQDN 作为首选项值：
+
** 名称： `mVIP_FQDN`
** 值： `集群 MVIP 的完全限定域名`
+
在此示例中， FQDN=storagecluster.my.org ：

+
[listing]
----
https://<Cluster_MVIP>/json-rpc/12.2?
method=CreateClusterInterfacePreference&name=mvip_fqdn&value=storagecluster.my.org
----


. 在管理节点上使用 REST API 更改管理节点设置：
+
.. 输入管理节点 IP 地址并后跟 ` /mnode/2/` ，以访问管理节点的 REST API UI
+
例如：

+
`https://<management_node_IP>/mnode/2/`

.. 单击 * 授权 * 或任何锁定图标，然后输入集群用户名和密码。
.. 输入客户端 ID `mnode-client` 。
.. 单击 * 授权 * 开始会话，然后关闭窗口。
.. 从服务器列表中，选择 `mnode2` 。
.. 单击 * 获取 /settings* 。
.. 单击 * 试用 * 。
.. 单击 * 执行 * 。
.. 记录响应正文中报告的所有代理设置。
.. 单击 * PUT/setttings* 。
.. 单击 * 试用 * 。
.. 在请求正文区域中，输入管理节点 FQDN 作为 `mnode_fqdn` 参数的值。
.. 输入先前在请求正文的其余参数中记录的任何代理设置值。如果将代理参数留空或未将其包含在请求正文中，则现有代理设置将被删除。
.. 单击 * 执行 * 。
+
....
== Find more information
* https://www.netapp.com/data-storage/solidfire/documentation[SolidFire and Element Resources page^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
....



