---
permalink: esds/concept_esds_networking_best_practices.html 
sidebar: sidebar 
keywords: solidfire esds, software-defined storage, networks, linux host routing, networking 
summary: 在安装 SolidFire ESDS 之前，您应在运行 RHEL 的存储节点上设置所需的网络。您负责环境中的网络路由。您可以使用作为框架提供的最佳实践。 
---
= 网络配置注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在安装 SolidFire ESDS 之前，您应在运行 RHEL 的存储节点上设置所需的网络。您负责环境中的网络路由。您可以使用作为框架提供的最佳实践。

[IMPORTANT]
====
* 使用绑定或绑定的接口。
* 对集群中的所有节点使用相同的接口名称（例如： team-mgt 表示每个节点的管理接口，而 team-stg 表示每个节点的存储接口）。
* 确保 NetworkManager 正在运行。
* 确保已在所有存储节点上安装 NetworkManager-dispater-routing-rules 软件包，以便进行基于策略的路由。
* 请参见 https://www.netapp.com/us/media/tr-4763.pdf["NetApp SolidFire 存储系统上的网络连接和网络维护最佳实践"]。
* 在每个节点上配置管理和存储网络，以便通过绑定或组配置使用多个冗余物理接口。


====
有关网络绑定的信息，请参见 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/ch-configure_network_teaming["配置网络绑定"^]。默认情况下，所有存储节点 10GbE 接口均已启用，最大传输单元（ MTU ）为 9000 字节。为了获得最佳性能，请为所有服务器端存储接口配置与 NetApp SolidFire 存储节点相同的 MTU 。您应将网络交换机配置为至少支持 9016 字节或更多的 MTU ，以考虑巨型帧开销以及通过网络正确转发。如果要更改此配置以支持较低的 MTU 设置，应联系 NetApp 支持部门。

有关 SolidFire ESDS 针对不同类型的流量所需的存储和管理网络的信息，请参见下表：

[cols="2*"]
|===
| 网络类型 | Description 


 a| 
存储网络
 a| 
* 包括所有存储 /iSCSI 流量。
* 如果要从位于不同第 3 层网络的主机挂载，或者计划在集群之间复制数据，则可以路由。
* 应在同一第 2 层广播域上配置网络接口。




 a| 
管理网络
 a| 
* 包括所有管理流量。
* 如果要从其他第 3 层网络访问集群 API 或 UI ，则可以路由。
* 应在同一第 2 层广播域上配置网络接口。
* 应使用 MTU 至少为 1500 字节的网络接口卡进行配置。


|===

TIP: 有关配置主机网络的示例和提示，请参见 link:task_esds_configure_the_interface_config_files.adoc["此处"]。



== 了解更多信息

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 资源页面"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["早期版本的 NetApp SolidFire 和 Element 产品的文档"^]

