---
permalink: esds/reference_esds_containerlogs.html 
sidebar: sidebar 
keywords: element, solidfire esds, get container logs, sds containers 
summary: 了解有关 SolidFire ESDS 容器以及从何处获取与其关联的日志的详细信息。此处提供的信息可帮助您开始收集日志以进行故障排除。最好联系 NetApp 支持部门，让精通日志分析的经过培训的工程师帮助解决问题。 
---
= 收集容器日志
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解有关 SolidFire ESDS 容器以及从何处获取与其关联的日志的详细信息。此处提供的信息可帮助您开始收集日志以进行故障排除。最好参与进来 https://www.netapp.com/company/contact-us/support/["NetApp 支持"^]，经过培训且精通日志分析的工程师可以帮助解决问题。

SolidFire ESDS 包括以下容器：

* Element 容器（`Element` ）：将所有 Element 服务托管在一个容器中。
* Element auth 容器（`element_auth` ）：为管理 UI 提供多因素身份验证（ Multifactor Authentication ， MFA ）和会话身份验证令牌。
* 网络 watchdog 容器（ `sfnetwd` ）：提供本地 Element 实例的检测信号监控以及虚拟 IP （ MVIP 和 SVIP ）的故障转移。


要通过 SSH 访问 ESDS 节点上的容器，节点所有者应启用 SSH 并提供登录凭据。通过 SSH 访问主机系统后，您可以使用 `podman ps` 命令检查一个或多个容器的状态。请参见以下示例。

[listing]
----
# podman ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
f6b8817c024a localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 10 seconds ago sfnetwd
c3fed6141259 localhost/solidfire-auth:12.2.0.777 --config /sf/etc/... 11 seconds ago Up 11 seconds ago element_auth
1ffa8289c701 localhost/solidfire-element:12.2.0.777 --config /sf/etc/... 12 seconds ago Up 12 seconds ago element
#
----

IMPORTANT: 如果其中一个容器未启动或运行，请勿使用 Podman 直接控制（停止或启动）容器。Element 软件通过 SolidFire systemd` 服务单元进行控制。此服务使用 `elementctl` 来编排在三个 Element 容器中运行的软件。在任何节点上启动和停止 Element 软件时，建议使用 `systemctl` 来控制主机上的 SolidFire 服务，并且此方法受支持；但是，只能在支持人员的指导下在实时集群上执行此操作。

与 SolidFire ESDS 相关的所有日志均可在主机上的 ` /var/log/solidfire/` 中找到，该日志会在各个容器实例中保留。此目录包含 Element 容器中的日志，并包含 `element_auth/` 和 `sfnetwd/` 子目录，这些子目录分别包含 `element_auth` 和 `sfnetwd` 容器中的日志。在容器内部，您可以通过 ` /var/log` 访问容器专用的日志。



=== 使用 NetApp Hybrid Cloud Control UI 收集日志

您可以收集日志并发送给 NetApp 支持部门，以帮助诊断 SolidFire ESDS 集群的问题。

收集日志时，请记住以下注意事项：

* 请勿使用 Podman 命令收集日志。
* NetApp 支持使用一个收集来收集主机日志。为了获得最佳支持体验，您应安装一个 Collect 。


.步骤
. 在Web浏览器中打开管理节点的IP地址。例如：
+
[listing]
----
https://[management node IP address]
----
. 通过提供存储集群管理员凭据登录到 NetApp Hybrid Cloud Control 。
. 从信息板中，选择右上角的菜单。
. 选择 * 收集日志 * 。
. 在 * 日期范围 * 下拉菜单中选择一个日期范围，以指定日志应包含的日期。
+
如果指定自定义开始日期，则可以选择开始日期范围的日期。将收集从该日期到目前为止的日志。

. 在 * 日志收集 * 部分中，选择存储集群或特定存储节点。
. 选择 * 收集日志 * 以开始收集日志。
+
日志收集在后台运行，页面将显示进度。

+

NOTE: 根据您收集的日志，进度条可能会以特定百分比保留几分钟，或者在某些时刻进度非常慢。

. 选择 * 下载日志 * 以下载日志包。
+
日志包采用压缩的 UNIX ` .tgz` 文件格式。





== 了解更多信息

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 资源页面"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["早期版本的 NetApp SolidFire 和 Element 产品的文档"^]

