---
permalink: esds/reference_esds_sf_sds_config_file.html 
sidebar: sidebar 
keywords: element, solidfire esds, hardware components, configuration file 
summary: 每个节点都有一个 sf_sSD_config.yaml 文件，其中包含您指定要由 SolidFire ESDS 服务使用的硬件列表。更换驱动器后，您必须在此文件中为更换驱动器的节点添加替代驱动器信息。此文件存储在 /opt/sf/ 中。此文件包含有关节点中驱动器的所有信息。每次添加新驱动器时，必须在此文件中输入新驱动器的详细信息。 
---
= sf_sSD_config.yaml 文件的内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每个节点都有一个 `sf_sSD_config.yaml` 文件，其中包括您指定要由 SolidFire ESDS 服务使用的硬件列表。更换驱动器后，您应在此文件中为更换驱动器的节点添加更换驱动器信息。此文件存储在 ` /opt/sf/` 中。此文件包含有关节点中驱动器的所有信息。每次添加新驱动器时，都应在此文件中输入新驱动器的详细信息。

以下是文件的 * 必填 * 内容：

[cols="4*"]
|===
| 密钥 | Default | Type | Description 


 a| 
架构版本
 a| 
2.0
 a| 
string
 a| 
文件的架构版本号。



 a| 
网络
 a| 
不适用
 a| 
列表
 a| 
允许的值： managementInterface ， storageInterface



 a| 
管理接口
 a| 
"team0"
 a| 
string
 a| 
用于管理和集群管理流量的预配置冗余主机操作系统网络接口的名称。



 a| 
存储接口
 a| 
"Team1"
 a| 
string
 a| 
用于存储网络流量（ iSCSI 流量）的预配置冗余主机操作系统网络接口的名称。



 a| 
数据驱动器
 a| 
不适用
 a| 
列表
 a| 
SolidFire ESDS 正在使用的物理存储设备的主机操作系统路径列表。您可以将其指定为块或 NVMe 设备的完整路径。以下是受支持的完整路径示例： /dev/disk/by-id/ww-xxxx-xxxx-example ， /dev/disk/by-uid/nve-xxxx-xxxxx 示例和 /dev/sda1



 a| 
缓存设备
 a| 
不适用
 a| 
列表
 a| 
SolidFire ESDS 用作缓存设备的物理设备的主机操作系统路径。您应将其指定为列表条目。以下是受支持的完整路径示例： /dev/disk/by-id/NVMe-NVMe.8086-XXXXX-XXXXX-XXXXXX-example

|===


== 了解更多信息

* https://www.netapp.com/data-storage/solidfire/documentation/["NetApp SolidFire 资源页面"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["早期版本的 NetApp SolidFire 和 Element 产品的文档"^]

