---
permalink: api/reference_element_api_addclusteradmin.html 
sidebar: sidebar 
keywords: addclusteradmin,cluster,admin,administrator,adding,add 
summary: 您可以使用 AddClusterAdmin 方法添加新的集群管理员帐户。集群管理员可以通过 API 和管理工具管理集群。集群管理员是完全独立的，与标准租户帐户无关。 
---
= 添加 ClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `AddClusterAdmin` 方法添加新的集群管理员帐户。集群管理员可以通过 API 和管理工具管理集群。集群管理员是完全独立的，与标准租户帐户无关。

可以将每个集群管理员限制为 API 的一部分。您应该对不同的用户和应用程序使用多个集群管理员帐户。最佳做法是，为每个集群管理员授予所需的最低权限；这样可以减少凭据损坏的潜在影响。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
访问
 a| 
控制集群管理员可以使用的方法。
 a| 
string array
 a| 
无
 a| 
是的。



 a| 
接受 Eula
 a| 
接受最终用户许可协议。设置为 true 可向系统添加集群管理员帐户。如果省略或设置为 false ，则方法调用将失败。
 a| 
boolean
 a| 
无
 a| 
是的。



 a| 
属性
 a| 
名称 / 值对列表，采用 JSON 对象格式。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
password
 a| 
用于对此集群管理员进行身份验证的密码。
 a| 
string
 a| 
无
 a| 
是的。



 a| 
username
 a| 
此集群管理员的唯一用户名。长度必须介于 1 到 1024 个字符之间。
 a| 
string
 a| 
无
 a| 
是的。

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
clusterAdminID
 a| 
新创建的集群管理员的 ClusterAdminID 。
 a| 
整型

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
  "method": "AddClusterAdmin",
  "params": {
    "username": "joeadmin",
    "password": "68!5Aru268)$",
    "attributes": {},
    "acceptEula": true,
    "access": ["volumes", "reporting", "read"]
  },
  "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
   "id":1,
  "result" : {
    "clusterAdminID": 2
   }
}
----


== 自版本以来的新增功能

9.6



== 了解更多信息

xref:reference_element_api_app_b_access_control.adoc[访问控制]
