---
permalink: api/reference_element_api_modifysnapshot.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapshot,attributes,attribute 
summary: 您可以使用 ModifySnapshot 更改当前分配给快照的属性。您也可以使用此方法将读 / 写 \ （源 \ ）卷上创建的快照远程复制到运行 Element 软件的目标存储集群。 
---
= ModifySnapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `ModfySnapshot` 更改当前分配给快照的属性。您还可以使用此方法将读 / 写（源）卷上创建的快照远程复制到运行 Element 软件的目标存储集群。



== Parameters

此方法具有以下输入参数：

|===


| Name | Description | Type | 默认值 | Required 


 a| 
启用远程复制
 a| 
用于将创建的快照复制到远程存储集群。可能值：

* `true` ：快照将复制到远程存储。
* `false` ：快照不会复制到远程存储。

 a| 
boolean
 a| 
false
 a| 
否



 a| 
到期时间
 a| 
指定删除快照的时间。不能用于保留。如果未指定原始快照的 expirationTime 或保留，则该快照不会过期。时间格式为基于时间的到期日期的 ISO 8601 日期字符串，否则它不会过期。如果值为 null ，则会永久保留快照。值为 ifo 会使快照以先出先出（ FIFO ）为基础进行保留，与卷上的其他 FIFO 快照相比。如果没有可用的 FIFO 空间， API 将失败。
 a| 
ISO 8601 日期字符串
 a| 
无
 a| 
否



 a| 
name
 a| 
快照的名称。如果未输入任何名称，则会使用创建快照的日期和时间。允许的最大名称长度为 255 个字符。
 a| 
string
 a| 
无
 a| 
否



 a| 
snapMirrorLabel
 a| 
SnapMirror 软件用于在 SnapMirror 端点上指定快照保留策略的标签。
 a| 
string
 a| 
无
 a| 
否



 a| 
snapshotId
 a| 
快照的标识符。
 a| 
string
 a| 
无
 a| 
是的。

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
Snapshot
 a| 
包含有关新修改快照的信息的对象。
 a| 
xref:reference_element_api_snapshot.adoc[Snapshot]

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
  "method": "ModifySnapshot",
  "params": {
    "snapshotID": 3114,
    "enableRemoteReplication": "true",
    "name" : "Chicago"
  },
  "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "snapshot": {
      "attributes": {},
      "checksum": "0x0",
      "createTime": "2016-04-04T17:26:20Z",
      "enableRemoteReplication": true,
      "expirationReason": "None",
      "expirationTime": null,
      "groupID": 0,
      "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
      "name": "test1",
      "snapshotID": 3114,
      "snapshotUUID": "5809a671-4ad0-4a76-9bf6-01cccf1e65eb",
      "status": "done",
      "totalSize": 5000658944,
      "virtualVolumeID": null,
      "volumeID": 1
    }
  }
}
----


== 自版本以来的新增功能

9.6
