---
permalink: api/reference_element_api_authsessioninfo.html 
sidebar: sidebar 
keywords: objects,object,authSessionInfo 
summary: authSessionInfo 对象包含有关身份验证会话的信息。 
---
= authSessionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
authSessionInfo 对象包含有关身份验证会话的信息。



== 对象成员

此对象包含以下成员：

|===
| Name | Description | Type 


 a| 
访问组列表
 a| 
用户的访问组列表。
 a| 
string array



 a| 
authMethod
 a| 
集群管理员用户拥有的授权类型。可能值：

* LDAP —通过 LDAP 进行身份验证。
* cluster —通过存储在集群数据库中的用户名和密码进行身份验证。
* IdP —通过第三方身份提供程序进行身份验证。

 a| 
string



 a| 
clusterAdminID
 a| 
与此会话关联的集群管理员 ID 列表。对于与 LDAP 或第三方身份提供程序（ IdP ）相关的会话，此会话将是与此会话关联的匹配集群管理员 ID 的聚合列表。
 a| 
整型数组



 a| 
finalTimeout
 a| 
会话无效的时间。此时间在创建会话时设置，无法更改。
 a| 
string



 a| 
idpConfigVersion
 a| 
创建会话时的 IdP 配置版本。
 a| 
整型



 a| 
lastAccessTimeout
 a| 
会话因非活动而变得无效的时间。访问会话以供使用时，会话将设置为新值，直到会话因达到 finalTimeout 而变得无效为止。
 a| 
string



 a| 
sessionCreationTime
 a| 
创建会话的时间。
 a| 
string



 a| 
会话 ID
 a| 
此会话的 UUID 。
 a| 
UUID



 a| 
username
 a| 
与此会话关联的用户名。对于与 LDAP 相关的会话，此 DN 将为用户的 LDAP DN 。对于与第三方 IdP 相关的会话，此名称 - 值对为任意名称 - 值对，将用于在会话中执行审核操作。它不一定与集群上的集群管理员名称匹配。例如， SAML 主题名称 ID ，但这取决于 IdP 的配置以及 SAML 断言的结果内容。
 a| 
string

|===