---
permalink: api/reference_element_api_getclustercapacity.html 
sidebar: sidebar 
keywords: cluster,capacity,getting,get,measurements,measure,deduplication,GetClusterCapacity 
summary: 您可以使用 GetClusterCapacity 返回整个存储集群的高级别容量测量结果。此方法将返回可用于计算 Element Web UI 中显示的效率速率的字段。您可以在脚本中使用效率计算来返回精简配置，重复数据删除，数据压缩和整体效率的效率比率。 
---
= GetClusterCapacity
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `GetClusterCapacity` 返回整个存储集群的高级别容量测量结果。此方法将返回可用于计算 Element Web UI 中显示的效率速率的字段。您可以在脚本中使用效率计算来返回精简配置，重复数据删除，数据压缩和整体效率的效率比率。



== 效率计算

使用以下公式计算精简配置，重复数据删除和数据压缩。这些公式适用于 Element 8.2 及更高版本。

* thinProvisioningFactor = （非零锁定 + 零锁定） / 非零锁定
* deDuplicationFactor = （非 ZeroBlocks + snapshotNonZeroBlocks ） / uniqueBlocks
* compressionFactor = （ uniqueBlocks * 4096 ） / （ uniqueBlocksUsedSpace * 0.93 ）




== 整体效率比率计算

使用以下等式通过精简配置，重复数据删除和数据压缩效率计算的结果计算整体集群效率。

* efficiencyFactor = thinProvisioningFactor * deDuplicationFactor * compressionFactor




== Parameters

此方法没有输入参数。



== 返回值

此方法具有以下返回值：

|===
| Name | Description | Type 


 a| 
集群容量
 a| 
存储集群的容量测量结果。
 a| 
xref:reference_element_api_clustercapacity.adoc[集群容量]

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
   "method": "GetClusterCapacity",
   "params": {},
   "id" : 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "clusterCapacity": {
      "activeBlockSpace": 236015557096,
      "activeSessions": 20,
      "averageIOPS": 0,
      "clusterRecentIOSize": 0,
      "currentIOPS": 0,
      "maxIOPS": 150000,
      "maxOverProvisionableSpace": 259189767127040,
      "maxProvisionedSpace": 51837953425408,
      "maxUsedMetadataSpace": 404984011161,
      "maxUsedSpace": 12002762096640,
      "nonZeroBlocks": 310080350,
      "peakActiveSessions": 20,
      "peakIOPS": 0,
      "provisionedSpace": 1357931085824,
      "snapshotNonZeroBlocks": 0,
      "timestamp": "2016-10-17T21:24:36Z",
      "totalOps": 1027407650,
      "uniqueBlocks": 108180156,
      "uniqueBlocksUsedSpace": 244572686901,
      "usedMetadataSpace": 8745762816,
      "usedMetadataSpaceInSnapshots": 8745762816,
      "usedSpace": 244572686901,
      "zeroBlocks": 352971938
    }
  }
}
----


== 自版本以来的新增功能

9.6
