---
permalink: api/reference_element_api_modifyvolume.html 
sidebar: sidebar 
keywords: volumes,volume,modifying,modify,change,changing,edit,editing,modifyvolume,settings 
summary: 您可以使用 ModifyVolume 方法修改现有卷上的设置。您可以一次修改一个卷，并且更改会立即生效。 
---
= ModifyVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `MmodifyVolume` 方法修改现有卷上的设置。您可以一次修改一个卷，并且更改会立即生效。

如果在修改卷时未指定 QoS 值，则这些值将保持修改前的相同。您可以通过运行 `GetDefaultQoS` 方法来检索新创建卷的默认 QoS 值。

如果需要增加要复制的卷的大小，请按以下顺序执行此操作，以防止出现复制错误：

. 增加具有 replicationTarget 访问权限的卷的大小。
. 增加具有读写访问权限的源或卷的大小。


确保目标卷和源卷的大小相同。


NOTE: 如果将访问状态更改为 locked 或 replicationTarget ，则所有现有 iSCSI 连接都将终止。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
volumeId
 a| 
要修改的卷的卷 ID 。
 a| 
整型
 a| 
无
 a| 
是的。



 a| 
访问
 a| 
允许对卷进行访问。可能值：

* `readOnly` ：仅允许执行读取操作。
* `readWrite` ：允许读取和写入。
* `locked` ：不允许读取或写入。如果未指定，则访问值不会更改。
* `replicationTarget` ：将卷标识为一组配对卷的目标卷。如果卷未配对，则访问状态为 locked 。如果未指定值，则访问值不会更改。
* `snapMirrorTarget` ：将卷标识为 SnapMirror 复制的目标卷。

 a| 
string
 a| 
无
 a| 
否



 a| 
accountId
 a| 
将卷重新分配到的帐户 ID 。如果未指定任何帐户，则会使用先前的帐户名称。
 a| 
整型
 a| 
无
 a| 
否



 a| 
associateWithQoSPolicy
 a| 
将卷与指定的 QoS 策略相关联。可能值：

* `true` ：将卷与 QoSPolicyID 参数中指定的 QoS 策略关联。
* `false` ：不要将卷与 QoSPolicyID 参数中指定的 QoS 策略相关联。如果为 false ，则无论是否在 QoSPolicy 参数中指定 QoS 策略，都会删除任何现有策略关联。

 a| 
boolean
 a| 
无
 a| 
否



 a| 
属性
 a| 
名称 - 值对列表，采用 JSON 对象格式。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
CREATETIME
 a| 
要设置为新卷创建日期的 ISO 8601 日期字符串。如果 setCreateTime 设置为 true ，则为必需项。
 a| 
ISO 8601 字符串
 a| 
无
 a| 
否



 a| 
启用 SnapMirrorReplication
 a| 
确定卷是否可用于 SnapMirror 端点的复制。可能值：

* `true`
* `false`

 a| 
boolean
 a| 
false
 a| 
否



| 五个大小 | 指定卷支持的最大先出（ FIFO ）快照数。请注意， FIFO 快照和非 FIFO 快照都使用卷上相同的可用快照插槽池。使用此选项可限制可用快照插槽的 FIFO 快照消耗量。请注意，您不能将此值修改为小于当前的 FIFO 快照计数。 | 整型 | 无 | 否 


| 最小大小 | 指定仅为先出（ First-in-First-out ， FIFO ）快照预留的快照插槽数量。由于 FIFO 和非 FIFO 快照共享同一个池，因此 minFIFO 参数会将可能的非 FIFO 快照总数减少相同的量。请注意，您不能修改此值，使其与当前非 FIFO 快照计数冲突。 | 整型 | 无 | 否 


 a| 
模式
 a| 
卷复制模式。可能值：

* `asynch` ：等待系统确认数据存储在源上，然后再写入目标。
* `sync` ：不等待源的数据传输确认开始向目标写入数据。

 a| 
string
 a| 
无
 a| 
否



 a| 
QoS
 a| 
此卷的新服务质量设置。如果未指定，则不会更改 QoS 设置。可能值：

* `minIOPS`
* `maxIOPS`
* `突发 IOPS`

 a| 
xref:reference_element_api_qos.adoc[QoS]
 a| 
无
 a| 
否



 a| 
qosPolicyID
 a| 
应将 QoS 设置应用于指定卷的策略的 ID 。此参数与 QoS 参数不能共存。
 a| 
整型
 a| 
无
 a| 
否



 a| 
setCreateTime
 a| 
设置为 true 可更改记录的卷创建日期。
 a| 
boolean
 a| 
无
 a| 
否



 a| 
totalSize
 a| 
卷的新大小（以字节为单位）。1000000000 等于 1 GB 。大小将向上取整为最接近的兆字节大小。此参数只能用于增加卷的大小。
 a| 
整型
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
volume
 a| 
包含有关新修改卷的信息的对象。
 a| 
xref:reference_element_api_volume.adoc[volume]

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
  "method": "ModifyVolume",
  "params": {
     "volumeID": 5,
     "attributes": {
        "name1": "value1",
        "name2": "value2",
        "name3": "value3"
     },
     "qos": {
        "minIOPS": 60,
        "maxIOPS": 100,
        "burstIOPS": 150,
        "burstTime": 60
     },
      "access" :"readWrite"
     },
      "totalSize": 20000000000,
     "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
      "volume": {
          "access": "readWrite",
          "accountID": 1,
          "attributes": {
              "name1": "value1",
              "name2": "value2",
              "name3": "value3"
          },
          "blockSize": 4096,
          "createTime": "2016-03-28T16:16:13Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.1459181777648.5",
          "name": "1459181777648",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 150,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 60
          },
          "scsiEUIDeviceID": "6a79617900000005f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a79617900000005",
          "sliceCount": 1,
          "status": "active",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [
              1
          ],
          "volumeID": 5,
          "volumePairs": []
      }
  }
}
----


== 自版本以来的新增功能

9.6



== 了解更多信息

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
