---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: 可以使用 ListAuthSessionsByUsername 方法列出指定用户的所有身份验证会话。不属于访问组集群管理员 / 管理员权限的调用方只能列出自己的会话。具有 ClusterAdmins/Administrator 权限的调用程序可以列出属于任何用户的会话。 
---
= ListAuthSessionsByUsername
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `ListAuthSessionsByUsername` 方法列出指定用户的所有身份验证会话。不属于访问组集群管理员 / 管理员权限的调用方只能列出自己的会话。具有 ClusterAdmins/Administrator 权限的调用程序可以列出属于任何用户的会话。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
authMethod
 a| 
要列出的用户会话的身份验证方法。只有 ClusterAdmins/Administrator AccessGroup 中的调用程序才能提供此参数。可能值包括：

* * authMethod=Cluster* 指定 ClusterAdmin 用户名。
* * authMethod=ldap* 用于指定用户的 LDAP DN 。
* * authMethod=Idp* 指定用户的 IdP UUID 或 NameID 。如果 IdP 未配置为返回任一选项，则此选项将指定创建会话时发出的随机 UUID 。

 a| 
authMethod
 a| 
无
 a| 
是的。



 a| 
username
 a| 
用户的唯一标识符。
 a| 
string
 a| 
无
 a| 
是的。

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
会话
 a| 
身份验证会话的会话信息列表。
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== 自版本以来的新增功能

12.0
