---
permalink: api/reference_element_api_setprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,setting protection domains 
summary: 您可以使用 SetProtectionDomainLayout 方法将节点分配给自定义保护域。 
---
= SetProtectionDomainLayout
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `SetProtectionDomainLayout` 方法将节点分配给自定义保护域。

必须为集群中的所有活动节点提供信息，并且不能为非活动节点提供任何信息。必须将给定机箱中的所有节点分配到同一个自定义保护域。必须为所有节点提供相同的 protectionDomainType 。不应包括节点和机箱等非自定义的 protectionDomainTypes 。如果提供了其中任一项，则会忽略自定义保护域，并返回相应的错误。


NOTE: 以下配置不支持自定义保护域：

* 包含共享机箱的存储集群
* 双节点存储集群


如果在具有这些配置的存储集群上使用此方法，则会返回错误。



== 参数

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
保护域布局
 a| 
每个节点的保护域信息。
 a| 
JSON 列表 link:reference_element_api_nodeprotectiondomains.md#GUID-3750B3B8-6A66-402F-85F1-E828005084BB["nodeProtectionDomains"] 对象。
 a| 
无
 a| 
是的。

|===


== 返回值

此方法具有以下返回值：

|===
| Name | Description | Type 


 a| 
保护域布局
 a| 
节点列表，每个节点及其关联的保护域。
 a| 
JSON 列表 link:reference_element_api_nodeprotectiondomains.md#GUID-3750B3B8-6A66-402F-85F1-E828005084BB["nodeProtectionDomains"] 对象。

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
  "id": 1,
  "method": "SetProtectionDomainLayout",
  "params": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== 自版本以来的新增功能

12.0
