---
permalink: api/reference_element_api_disablemaintenancemode.html 
sidebar: sidebar 
keywords: disable,maintenance,mode 
summary: 您可以使用 DisableMaintenanceMode 方法使存储节点退出维护模式。只有在完成维护且节点处于联机状态后，才应禁用维护模式。 
---
= 禁用维护模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `DisableMaintenanceMode` 方法将存储节点退出维护模式。只有在完成维护且节点处于联机状态后，才应禁用维护模式。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
nodes
 a| 
要退出维护模式的存储节点 ID 列表。
 a| 
整型数组
 a| 
无
 a| 
是的。

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
异步处理
 a| 
您可以使用 GetAsyncResult 方法检索此 asyncHandle 并确定维护模式过渡完成的时间。
 a| 
整型



 a| 
当前模式
 a| 
节点的当前维护模式状态。可能值：

* Disabled ：尚未请求任何维护。
* FailedToRecover ：节点无法从维护模式恢复。
* Unexpected ：发现节点脱机，但处于 Disabled 模式。
* RecoveringFromMaintenance ：节点正在从维护模式恢复。
* PreparingForMaintenance ：正在执行操作以准备节点以执行维护。
* ReadyForMaintenance ：节点已准备好执行维护。

 a| 
维护模式（字符串）



 a| 
重新要求模式
 a| 
节点请求的维护模式状态。可能值：

* Disabled ：尚未请求任何维护。
* FailedToRecover ：节点无法从维护模式恢复。
* Unexpected ：发现节点脱机，但处于 Disabled 模式。
* RecoveringFromMaintenance ：节点正在从维护模式恢复。
* PreparingForMaintenance ：正在执行操作以准备节点以执行维护。
* ReadyForMaintenance ：节点已准备好执行维护。

 a| 
维护模式（字符串）

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
  "method": "DisableMaintenanceMode",
  "params": {
    "nodes": [6]
  },
"id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "Disabled",
        "asyncHandle": 1,
        "currentMode": "Enabled"
    }
}
----


== 自版本以来的新增功能

12.2



== 了解更多信息

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["NetApp HCI 存储维护模式概念"^]
