---
permalink: api/reference_element_api_resyncsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,resync,resyncing,ResyncSnapMirrorRelationship 
summary: Element 软件 Web UI 使用 ResyncSnapMirrorRelationship 方法在源端点和目标端点之间建立或重新建立镜像关系。重新同步关系时，系统会删除目标卷上比通用快照副本更新的快照，然后将目标卷挂载为数据保护卷，并将通用快照副本作为导出的快照副本。 
---
= 重新同步 SnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 软件 Web UI 使用 `ResyncSnapMirrorRelationship` 方法在源端点和目标端点之间建立或重新建立镜像关系。重新同步关系时，系统会删除目标卷上比通用快照副本更新的快照，然后将目标卷挂载为数据保护卷，并将通用快照副本作为导出的快照副本。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
snapMirrorEndpointID
 a| 
与 Element 存储集群通信的远程 ONTAP 存储系统的端点 ID 。
 a| 
整型
 a| 
无
 a| 
是的。



 a| 
目标卷
 a| 
SnapMirror 关系中的目标卷。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
无
 a| 
是的。



 a| 
maxTransferRate
 a| 
指定卷之间的最大数据传输速率，以 KB/ 秒为单位。默认值 0 为无限制，允许 SnapMirror 关系充分利用可用网络带宽。
 a| 
整型
 a| 
无
 a| 
否



 a| 
源卷
 a| 
SnapMirror 关系中的源卷。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
snapMirrorRelationship
 a| 
包含有关已重新同步的 SnapMirror 关系的信息的对象。
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== 自版本以来的新增功能

10.1
