---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: 您可以使用 ListVolumes 方法获取集群中的卷列表。您可以使用可用参数指定要在列表中返回的卷。 
---
= ListVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `ListVolumes` 方法获取集群中的卷列表。您可以使用可用参数指定要在列表中返回的卷。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
—帐户
 a| 
仅返回由此处指定的帐户拥有的卷。与 volumeIDs 参数不能共存。
 a| 
整型数组
 a| 
无
 a| 
否



 a| 
包括 VirtualVolumes
 a| 
默认情况下，响应中包含虚拟卷。要排除虚拟卷，请设置为 false 。
 a| 
boolean
 a| 
true
 a| 
否



 a| 
已完成
 a| 
返回已配对或未配对的卷。可能值：

* true ：返回所有已配对卷。
* false ：返回所有未配对的卷。

 a| 
boolean
 a| 
无
 a| 
否



 a| 
limit
 a| 
用于设置返回的卷结果的最大数量。与 volumeIDs 参数不能共存。
 a| 
整型
 a| 
10000
 a| 
否



 a| 
startVolumeID
 a| 
仅返回 ID 大于或等于此值的卷。与 volumeIDs 参数不能共存。
 a| 
整型
 a| 
无
 a| 
否



 a| 
volumeIds
 a| 
卷 ID 列表。如果指定此参数，则其他参数仅对这组卷运行。与 accounts ， startVolumeID 和 limit 参数互斥。
 a| 
整型数组
 a| 
否
 a| 
否



 a| 
volumeName
 a| 
仅返回与卷名称匹配的卷对象信息。
 a| 
string
 a| 
否
 a| 
否



 a| 
卷状态
 a| 
仅返回状态等于状态值的卷。可能值：

* 正在创建
* 快照
* 活动
* 已删除

 a| 
string
 a| 
否
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
volumes
 a| 
卷列表。
 a| 
xref:reference_element_api_volume.adoc[volume] 数组

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== 自版本以来的新增功能

9.6
