---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: 您可以使用 TestPing 方法测试使用 ICMP 数据包在 1G 和 10G 接口上与集群中所有节点的网络连接。此测试会根据网络配置中的 MTU 设置对每个数据包使用适当的 MTU 大小。TestPing 不会创建临时 VLAN 接口。 
---
= TestPing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `TestPing` 方法测试使用 ICMP 数据包在 1G 和 10G 接口上与集群中所有节点的网络连接。此测试会根据网络配置中的 MTU 设置对每个数据包使用适当的 MTU 大小。`TestPing` 不会创建临时 VLAN 接口。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
尝试次数
 a| 
指定系统应重复执行测试 ping 的次数。
 a| 
整型
 a| 
5.
 a| 
否



 a| 
主机
 a| 
指定要 ping 的设备的地址或主机名列表，以逗号分隔。如果未指定任何主机，则此方法将对存储集群中的主机执行 ping 操作。
 a| 
string
 a| 
无
 a| 
否



 a| 
接口
 a| 
应从中发送 ping 的现有（基本）接口。可能值：

* `Bond10G` ：从绑定 10G 接口发送 ping 。
* `Bond1G` ：从绑定 1G 接口发送 ping 。

 a| 
string
 a| 
无
 a| 
否



 a| 
packetSize
 a| 
指定要在发送到每个 IP 的 ICMP 数据包中发送的字节数。字节数必须小于网络配置中指定的最大 MTU 。
 a| 
整型
 a| 
无
 a| 
否



 a| 
PingTimeoutMsec
 a| 
指定等待每个 ping 响应的毫秒数。
 a| 
整型
 a| 
500 毫秒
 a| 
否



 a| 
禁止分段
 a| 
为 ICMP 数据包启用 DF （ Do not Fragment ）标志。
 a| 
boolean
 a| 
false
 a| 
否



 a| 
sourceAddressV4
 a| 
要在 ICMP ping 数据包中使用的源 IPv4 地址。
 a| 
string
 a| 
无
 a| 
否



 a| 
sourceAddressV6
 a| 
要在 ICMP ping 数据包中使用的源 IPv6 地址。
 a| 
string
 a| 
无
 a| 
否



 a| 
总计超时秒
 a| 
指定在发出下一次 ping 尝试或结束此过程之前 ping 应等待系统响应的时间（以秒为单位）。
 a| 
整型
 a| 
5.
 a| 
否



 a| 
virtualNetworkTag
 a| 
发送 ping 数据包时要使用的 VLAN ID 。
 a| 
整型
 a| 
无
 a| 
否

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
详细信息
 a| 
列出节点能够与之通信的每个 IP 以及 ping 响应统计信息。
 a| 
JSON 对象

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== 自版本以来的新增功能

5.0
