---
permalink: api/reference_element_api_creategroupsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,snapshot,snapshots,CreateGroupSnapshot,group,create,creating 
summary: 您可以使用 CreateGroupSnapshot 为一组卷创建时间点副本。 
---
= CreateGroupSnapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `CreateGroupSnapshot` 创建一组卷的时间点副本。

您可以稍后将此快照用作备份或回滚，以确保卷组上的数据在创建快照的时间点保持一致。

* 集群填充度 *


NOTE: 如果集群填充度处于第 1 ， 2 或 3 阶段，则可以创建快照。当集群填充度达到第 4 或第 5 阶段时，您无法创建快照。



== Parameters

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
`属性`
 a| 
名称 - 值对列表，采用 JSON 对象格式。
 a| 
JSON 对象
 a| 
无
 a| 
否



 a| 
`enableRemoteReplication`
 a| 
指定是否将快照复制到远程存储。可能值：

* `true` ：快照将复制到远程存储。
* `false` ：快照不会复制到远程存储。

 a| 
boolean
 a| 
false
 a| 
否



| `ensureSerialCreation`  a| 
指定在执行上一个快照复制时不应创建快照。可能值包括：

* `true` ：这可确保一次仅复制一个快照。如果先前的快照复制仍在进行中，则创建新快照将失败。
* `false` ：默认值。如果另一个快照复制仍在进行中，则允许创建此快照。

| boolean | `false` | 否 


 a| 
`expirationTime`
 a| 
指定删除快照的时间。不能与 `retention` 配合使用。如果未指定 `expirationTime` 或 `retention` ，则快照不会过期。时间格式为基于时间的到期日期的 ISO 8601 日期字符串，否则它不会过期。如果值为 `null` ，则会永久保留快照。值 `ifo` 会使快照相对于卷上的其他 FIFO 快照以先入先出（ FIFO ）为基础进行保留。如果没有可用的 FIFO 空间， API 将失败。
 a| 
ISO 8601 日期字符串
 a| 
无
 a| 
否



 a| 
`名称`
 a| 
组快照的名称。如果未输入任何名称，则会使用创建组快照的日期和时间。允许的最大名称长度为 255 个字符。
 a| 
string
 a| 
无
 a| 
否



 a| 
`re保留`
 a| 
此参数与 `expirationTime` 参数相同，但时间格式为 HH ： mm ： ss如果未指定 `expirationTime` 或 `retention` ，则快照不会过期。
 a| 
string
 a| 
无
 a| 
否



 a| 
`snapMirrorLabel`
 a| 
SnapMirror 软件用于在 SnapMirror 端点上指定快照保留策略的标签。
 a| 
string
 a| 
无
 a| 
否



 a| 
`卷`
 a| 
要从中复制的卷映像的唯一 ID 。
 a| 
volumeID 数组
 a| 
无
 a| 
是的。

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
成员
 a| 
组中每个成员的校验和，卷 ID 和快照 ID 列表。有效值：

* checksum ：存储的快照中的数据的一个小字符串表示。此校验和可在稍后用于比较其他快照以检测数据中的错误。string
* snapshotID ：用于创建新快照的快照的唯一 ID 。快照 ID 必须来自给定卷上的快照。整型
* volumeID ：快照的源卷 ID 。整型

 a| 
JSON 对象数组



 a| 
groupSnapshotID
 a| 
新组快照的唯一 ID 。
 a| 
groupSnapshot ID



 a| 
groupSnapshot
 a| 
包含有关新创建的组快照的信息的对象。
 a| 
xref:reference_element_api_groupsnapshot.adoc[groupSnapshot]

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
   "method": "CreateGroupSnapshot",
   "params": {
      "volumes": [1,2]
   },
   "id": 1
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 1,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-04T22:43:29Z",
      "groupSnapshotID": 45,
      "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3323,
          "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
          "status": "done",
          "totalSize": 5000658944,
          "virtualVolumeID": null,
          "volumeID": 1
        },
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3324,
          "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
          "status": "done",
          "totalSize": 6001000448,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-04T22:43:29Z",
      "status": "done"
    },
    "groupSnapshotID": 45,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 3323,
        "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
        "volumeID": 1
      },
      {
        "checksum": "0x0",
        "snapshotID": 3324,
        "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
        "volumeID": 2
      }
    ]
  }
}
----


== 自版本以来的新增功能

9.6
