---
permalink: api/reference_element_api_createinitiators.html 
sidebar: sidebar 
keywords: create,creating,initiator,CreateInitiators,WWPN,IQN,initiators 
summary: 您可以使用 CreateInitiators 创建多个新启动程序 IQN 或全球通用端口名称（ WWPN ），并可选择为其分配别名和属性。使用 CreateInitiators 创建新启动程序时，您还可以将其添加到卷访问组中。 
---
= CreateInitiators
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `CreateInitiators` 创建多个新启动程序 IQN 或全球通用端口名称（ World Wide Port Name ， WWPN ），并可为其分配别名和属性。使用 `CreateInitiators` 创建新启动程序时，您还可以将其添加到卷访问组中。

如果操作无法创建参数中提供的启动程序之一，则该方法将返回错误，并且不会创建任何启动程序（无法部分完成）。



== 参数

此方法具有以下输入参数：

|===
| Name | Description | Type | 默认值 | Required 


 a| 
启动程序
 a| 
包含每个新启动程序特征的对象列表。对象：

* `alias` ：（可选）要分配给此启动程序的友好名称。string
* `attributes` ：（可选）要分配给此启动程序的一组 JSON 属性。（ JSON 对象）
* `chapUsername` ：（可选）此启动程序的唯一 CHAP 用户名。如果在创建期间未指定启动程序名称（ IQN ），并且 requireChap 为 true ，则默认为启动程序名称（ IQN ）。string
* `initiatorSecret` ：（可选）用于对启动程序进行身份验证的 CHAP 密钥。如果在创建期间未指定此密钥，并且 requireChap 为 true ，则默认为随机生成的密钥。string
* `name` ：（必需）要创建的启动程序的名称（ IQN 或 WWPN ）。string
* `requireChap` ：（可选）如果在会话登录期间需要对此启动程序执行 CHAP ，则为 True 。boolean
* `targetSecret` ：（可选）用于对目标进行身份验证的 CHAP 密钥（使用相互 CHAP 身份验证时）。如果在创建期间未指定此密钥，并且 requireChap 为 true ，则默认为随机生成的密钥。string
* `virtualNetworkID` ：（可选）与此启动程序关联的虚拟网络标识符的列表。如果定义了一个或多个虚拟网络，则此启动程序只能登录到这些虚拟网络。如果不定义任何虚拟网络，此启动程序可以登录到所有网络。
* `volumeAccessGroupID` ：（可选）要将此新创建的启动程序添加到的卷访问组的 ID 。整型

 a| 
JSON 对象数组
 a| 
无
 a| 
是的。

|===


== 返回值

此方法具有以下返回值：

|===


| Name | Description | Type 


 a| 
启动程序
 a| 
描述新创建启动程序的对象列表。
 a| 
xref:reference_element_api_initiator.adoc[启动程序] 数组

|===


== error

此方法可能会返回以下错误：

|===


| Name | Description 


 a| 
xInitiatorExists
 a| 
如果您选择的启动程序名称已存在，则返回此消息。

|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
  "id": 3291,
  "method": "CreateInitiators",
  "params": {
    "initiators": [
      {
        "name": "iqn.1993-08.org.debian:01:288170452",
        "alias": "example1"
      },
      {
        "name": "iqn.1993-08.org.debian:01:297817012",
        "alias": "example2"
      }
    ]
  }
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
  "id": 3291,
  "result": {
    "initiators": [
      {
        "alias": "example1",
        "attributes": {},
        "initiatorID": 145,
        "initiatorName": "iqn.1993-08.org.debian:01:288170452",
        "volumeAccessGroups": []
      },
      {
        "alias": "example2",
        "attributes": {},
        "initiatorID": 146,
        "initiatorName": "iqn.1993-08.org.debian:01:297817012",
        "volumeAccessGroups": []
      }
    ]
  }
}
----


== 自版本以来的新增功能

9.6



== 了解更多信息

xref:reference_element_api_listinitiators.adoc[ListInitiators]
